### ISSUE TITLE
Specified type of property cannot be automatically resolved to a sequelize data type. Please define the data type manually.

### ISSUE THREAD

**Issue by YogeshUmeshVaity** [RobinBuschmann/sequelize-typescript#1035]
# Issue
Error: `Specified type of property cannot be automatically resolved to a sequelize data type. Please define the data type manually`

## Versions

- sequelize: ^6.6.4
- sequelize-typescript: ^2.1.0
- typescript: ^4.0.2

## Issue type

- [x] bug report
- [ ] feature request

## Actual behavior

```
*ProjectPath*/node_modules/sequelize-typescript/dist/model/shared/model-service.js:64
    throw new Error(`Specified type of property '${propertyName}'
          ^
Error: Specified type of property 'products'
            cannot be automatically resolved to a sequelize data type. Please
            define the data type manually
    at Object.getSequelizeTypeByDesignType (*ProjectPath*/node_modules/sequelize-typescript/dist/model/shared/model-service.js:64:11)
    at annotate (*ProjectPath*/node_modules/sequelize-typescript/dist/model/column/column.js:32:44)
    at Column (*ProjectPath*/node_modules/sequelize-typescript/dist/model/column/column.js:14:9)
    at DecorateProperty (*ProjectPath*/node_modules/reflect-metadata/Reflect.js:553:33)
    at Object.decorate (*ProjectPath*/node_modules/reflect-metadata/Reflect.js:123:24)
    at __decorate (*ProjectPath*/src/models/user.ts:4:92)
    at Object.<anonymous> (*ProjectPath*/src/models/user.ts:27:5)
    at Module._compile (internal/modules/cjs/loader.js:1156:30)
    at Module.m._compile (*ProjectPath*/node_modules/ts-node/src/index.ts:1043:23)
    at Module._extensions..js (internal/modules/cjs/loader.js:1176:10)
```

## Expected behavior
Project should compile normally without the error.

## Steps to reproduce and related code
Create one-to-many relationship between the two models:

User.ts

```
@Table
export class User extends Model {
    @Column({ primaryKey: true })
    id!: string

    @Column
    name!: string

    @Column
    email!: string

    @Column
    @HasMany(() => Product)
    products?: Product[]
}
```

Product.ts

```
@Table
export class Product extends Model {
    @Column({ primaryKey: true })
    id!: string

    @Column
    title!: string

    @Column({ type: DataType.DOUBLE })
    price!: number

    @Column
    imageUrl!: string

    @Column
    description?: string

    @ForeignKey(() => User)
    @Column
    createdByUserId!: string

    @BelongsTo(() => User)
    createdByUser!: User
}
```

**tsconfig.json**
```
{
  "compilerOptions": {
    "target": "es6",                          /* Specify ECMAScript target version: 'ES3' (default), 'ES5', 'ES2015', 'ES2016', 'ES2017', 'ES2018', 'ES2019', 'ES2020', or 'ESNEXT'. */
    "module": "commonjs",                     /* Specify module code generation: 'none', 'commonjs', 'amd', 'system', 'umd', 'es2015', 'es2020', or 'ESNext'. */
    "lib": ["es6"],                           /* Specify library files to be included in the compilation. */
    "allowJs": true,                          /* Allow javascript files to be compiled. */
    "outDir": "dist",                         /* Redirect output structure to the directory. */
    "rootDir": "src",                         /* Specify the root directory of input files. Use to control the output directory structure with --outDir. */
    /* Strict Type-Checking Options */
    "strict": true,                           /* Enable all strict type-checking options. */
    "noImplicitAny": true,                    /* Raise error on expressions and declarations with an implied 'any' type. */
    "esModuleInterop": true,                  /* Enables emit interoperability between CommonJS and ES Modules via creation of namespace objects for all imports. Implies 'allowSyntheticDefaultImports'. */
    /* Experimental Options */
    "experimentalDecorators": true,        /* Enables experimental support for ES7 decorators. */
    "emitDecoratorMetadata": true,         /* Enables experimental support for emitting type metadata for decorators. */
    /* Advanced Options */
    "resolveJsonModule": true,                /* Include modules imported with '.json' extension */
    "skipLibCheck": true,                     /* Skip type checking of declaration files. */
    "forceConsistentCasingInFileNames": true  /* Disallow inconsistently-cased references to the same file. */
  }
}
```

**Comment by YSHIDM** [comment]
Have you solved this problem?

**Comment by YogeshUmeshVaity** [comment]
> Have you solved this problem?

Yes, I removed @Column annotation from the products field and it worked.

**Comment by unicornware** [comment]
the docs indicate we should be able to use `@Column` without an issue. this seems like a bug.

**Comment by YSHIDM** [comment]
> > Have you solved this problem?
> 
> Yes, I removed @column annotation from the products field and it worked.

👌

**Comment by tavurth** [comment]
Please re-open this. Having the same issue and the suggested solution results in Sequelize complaining that the `@Column` tag is misssing.

**Comment by lla830126** [comment]
tsconfig.json added 
emitDecoratorMetadata: true <-- 
solved work!

**Comment by iamgabrielsoft** [comment]
i bet this is still a bug in Sequelize, please follow the StackOverflow solution its works
https://stackoverflow.com/a/68439775/18858864

**Comment by s-meunier** [comment]
> tsconfig.json added emitDecoratorMetadata: true <-- solved work!

the flag already exists in my config, but auto-resolving of the basic types doesn't work.
But for me only in combination with Node 16/18 and when using _tsx_.

I'm currently still trying to figure out, how to solve this - by keeping the automatism.
A simple way to solve it (and don't care about the resolving of the basic types): add the Sequelize DataType definition to each basic (string,number, ...) @Column decorators.

**Comment by lvegerano** [comment]
This is still a problem

**Comment by sergii-nosachenko** [comment]
Same problem `Error: Specified type of property 'id' cannot be automatically resolved to a sequelize data type. Please define the data type manually`. In my case, this column is not described as `@Column` as this is not obligatory.

**Comment by d00rsfan** [comment]
> Same problem `Error: Specified type of property 'id' cannot be automatically resolved to a sequelize data type. Please define the data type manually`. In my case, this column is not described as `@Column` as this is not obligatory.

Don't use **tsx**, instead use **ts-node** during run dev and tsc for build.
