### ISSUE TITLE
DefaultValue across Sequelize.fn

### ISSUE THREAD

**Issue by CocaColaBear** [RobinBuschmann/sequelize-typescript#110]
Hi. I have a problem.
I need to use database function for default column value.
If i use:
`@Default(Sequelize.fn("some_function"))`
I get an error: "_Error: Invalid value [object Object]_"
But if i place this to Column annotation then works fine. Example:
```
@Column({
    type: DataType.BIGINT,
    defaultValue: Sequelize.fn("some_function")}
)
```

**Comment by RobinBuschmann** [comment]
Hey @CocaColaBear, thanks for contributing. When does this error exactly appear?

**Comment by CocaColaBear** [comment]
@RobinBuschmann 
```
Error: Invalid value [object Object]
    at Object.escape (d:\test\node_modules\sequelize\lib\sql-string.js:50:11)
    at Object.attributeToSQL (d:\test\node_modules\sequelize\lib\dialects\postgres\query-generator.js:518:33)
    at Object.attributesToSQL (d:\test\node_modules\sequelize\lib\dialects\postgres\query-generator.js:584:45)
    at Promise.all.then.results (d:\test\node_modules\sequelize\lib\query-interface.js:146:42)
    at tryCatcher (d:\test\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (d:\test\node_modules\bluebird\js\release\promise.js:512:31)
    at Promise._settlePromise (d:\test\node_modules\bluebird\js\release\promise.js:569:18)
    at Promise._settlePromiseCtx (d:\test\node_modules\bluebird\js\release\promise.js:606:10)
    at Async._drainQueue (d:\test\node_modules\bluebird\js\release\async.js:138:12)
    at Async._drainQueues (d:\test\node_modules\bluebird\js\release\async.js:143:10)
    at Immediate.Async.drainQueues (d:\test\node_modules\bluebird\js\release\async.js:17:14)
    at tryOnImmediate (timers.js:624:5)
    at processImmediate [as _immediateCallback] (timers.js:596:5)
```

**Comment by RobinBuschmann** [comment]
Is this thrown while using `find`/`findAll` or while initialization of the model? Which sequelize-typescript version and which sequelize version are you using?

**Comment by CocaColaBear** [comment]
@RobinBuschmann initialization.
sequelize-typescript: 0.4.0
sequelize: 4.0.65

**Comment by RobinBuschmann** [comment]
Thank you. I will label this as a bug and will fix it soon.
