### ISSUE TITLE
Creating with associations

### ISSUE THREAD

**Issue by Deilan** [RobinBuschmann/sequelize-typescript#117]
How to [create with associations](http://docs.sequelizejs.com/manual/tutorial/associations.html#creating-with-associations)?

**Comment by Pritilender** [comment]
@Deilan what's the problem with the way described in docs?

**Comment by RobinBuschmann** [comment]
@Deilan See https://github.com/RobinBuschmann/sequelize-typescript#model-association

**Comment by Deilan** [comment]
See [repo](https://github.com/Deilan/sequelize-typescript-issue-117). The entities used here are from the docs.

1. `yarn install` or `npm install`
2. `npm start`


Main code:
```typescript
import "reflect-metadata";

import { Sequelize } from "sequelize-typescript";
import { tmpFileAsync } from "./tmp";

import Address from "./models/address";
import Product from "./models/product";
import User from "./models/user";

async function main(): Promise<void> {
    const { path, cleanupCallback } = await tmpFileAsync();
    // tslint:disable:object-literal-sort-keys
    const sequelize = new Sequelize({
        name: "db",
        dialect: "sqlite",
        username: "",
        password: "",
        storage: path,
    });
    // tslint:enable:object-literal-sort-keys
    sequelize.addModels([Product, User, Address]);
    await sequelize.sync();
    await createProduct();
    cleanupCallback();
}

async function createProduct(): Promise<Product> {
    // tslint:disable:object-literal-sort-keys
    const product = await Product.create<Product>({
        title: "Chair",
        user: {
            first_name: "Mick",
            last_name: "Broadstone",
            addresses: [{
                type: "home",
                line_1: "100 Main St.",
                city: "Austin",
                state: "TX",
                zip: "78704",
            }],
        },
    }, {
        include: [User, Address],
    });
    // tslint:enable:object-literal-sort-keys
    return product;
}

main();
```

The entities:
```typescript
import { Column, HasMany, Model, Sequelize, Table } from "sequelize-typescript";
import User from "./user";

@Table
export default class Product extends Model<Product> {
    @Column({ type: Sequelize.STRING })
    public title: string;

    @HasMany(() => User, { foreignKey: "productId" })
    public public: User[] = [];
}
```

```typescript
import { BelongsTo, Column, ForeignKey, HasMany, Model, Sequelize, Table } from "sequelize-typescript";
import Address from "./address";
import Product from "./product";

@Table
export default class User extends Model<User> {
    @Column({ type: Sequelize.STRING })
    public firstName: string;

    @Column({ type: Sequelize.STRING })
    public lastName: string;

    @Column
    @ForeignKey(() => Product)
    public productId: number;

    @BelongsTo(() => Product, { foreignKey: "productId" })
    public product: Product;

    @HasMany(() => Address, { foreignKey: "userId" })
    public addresses: Address[] = [];
}
```

```typescript
import { BelongsTo, Column, ForeignKey, Model, Sequelize, Table } from "sequelize-typescript";
import User from "./user";

@Table
export default class Address extends Model<Address> {
    @Column({ type: Sequelize.STRING })
    public type: string;
    @Column({ type: Sequelize.STRING })
    public line1: string;
    @Column({ type: Sequelize.STRING })
    public line2: string;
    @Column({ type: Sequelize.STRING })
    public city: string;
    @Column({ type: Sequelize.STRING })
    public state: string;
    @Column({ type: Sequelize.STRING })
    public zip: string;

    @Column
    @ForeignKey(() => User)
    public userId: number;

    @BelongsTo(() => User, { foreignKey: "userId" })
    public user: User;
}
```

Error, which occurs at `await Product.create<Product>()`:
```
Exception has occurred: EagerLoadingError
EagerLoadingError: Address is not associated to Product!
    at Function._getIncludedAssociation (c:\Dev2\sequelize-typescript-issue-117\node_modules\sequelize\lib\model.js:573:13)
    at Function._validateIncludedElement (c:\Dev2\sequelize-typescript-issue-117\node_modules\sequelize\lib\model.js:489:53)
    at options.include.options.include.map.include (c:\Dev2\sequelize-typescript-issue-117\node_modules\sequelize\lib\model.js:385:37)
    at Array.map (native)
    at Function._validateIncludedElements (c:\Dev2\sequelize-typescript-issue-117\node_modules\sequelize\lib\model.js:381:39)
    at Function.BaseModel.prepareInstantiationOptions (c:\Dev2\sequelize-typescript-issue-117\node_modules\sequelize-typescript\lib\models\BaseModel.js:100:84)
    at Model (c:\Dev2\sequelize-typescript-issue-117\node_modules\sequelize-typescript\lib\models\v4\Model.js:8:45)
    at Product (c:\Dev2\sequelize-typescript-issue-117\src\models\product.ts:16:9)
    at Function.build (c:\Dev2\sequelize-typescript-issue-117\node_modules\sequelize\lib\model.js:1916:12)
    at Function._target.(anonymous function) [as build] (c:\Dev2\sequelize-typescript-issue-117\node_modules\sequelize-typescript\lib\models\BaseModel.js:35:41)
    at Function.create (c:\Dev2\sequelize-typescript-issue-117\node_modules\sequelize\lib\model.js:1967:17)
    at Function._target.(anonymous function) [as create] (c:\Dev2\sequelize-typescript-issue-117\node_modules\sequelize-typescript\lib\models\BaseModel.js:35:41)
    at c:\Dev2\sequelize-typescript-issue-117\src\index.ts:23:26
    at Generator.next (<anonymous>)
    at c:\Dev2\sequelize-typescript-issue-117\src\index.ts:7:71
    at __awaiter (c:\Dev2\sequelize-typescript-issue-117\src\index.ts:3:12)
    at createProduct (c:\Dev2\sequelize-typescript-issue-117\src\index.ts:38:12)
    at c:\Dev2\sequelize-typescript-issue-117\src\index.ts:17:9
    at Generator.next (<anonymous>)
    at fulfilled (c:\Dev2\sequelize-typescript-issue-117\src\index.ts:4:58)
```

How to overcome that correctly?

**Comment by Deilan** [comment]
@Pritilender, @RobinBuschmann See [repo](https://github.com/Deilan/sequelize-typescript-issue-117). The entities used here are from the docs.

1. `yarn install` or `npm install`
2. `npm start`


Main code:
```typescript
import "reflect-metadata";

import { Sequelize } from "sequelize-typescript";
import { tmpFileAsync } from "./tmp";

import Address from "./models/address";
import Product from "./models/product";
import User from "./models/user";

async function main(): Promise<void> {
    const { path, cleanupCallback } = await tmpFileAsync();
    // tslint:disable:object-literal-sort-keys
    const sequelize = new Sequelize({
        name: "db",
        dialect: "sqlite",
        username: "",
        password: "",
        storage: path,
    });
    // tslint:enable:object-literal-sort-keys
    sequelize.addModels([Product, User, Address]);
    await sequelize.sync();
    await createProduct();
    cleanupCallback();
}

async function createProduct(): Promise<Product> {
    // tslint:disable:object-literal-sort-keys
    const product = await Product.create<Product>({
        title: "Chair",
        user: {
            first_name: "Mick",
            last_name: "Broadstone",
            addresses: [{
                type: "home",
                line_1: "100 Main St.",
                city: "Austin",
                state: "TX",
                zip: "78704",
            }],
        },
    }, {
        include: [User, Address],
    });
    // tslint:enable:object-literal-sort-keys
    return product;
}

main();
```

The entities:
```typescript
import { Column, HasMany, Model, Sequelize, Table } from "sequelize-typescript";
import User from "./user";

@Table
export default class Product extends Model<Product> {
    @Column({ type: Sequelize.STRING })
    public title: string;

    @HasMany(() => User, { foreignKey: "productId" })
    public public: User[] = [];
}
```

```typescript
import { BelongsTo, Column, ForeignKey, HasMany, Model, Sequelize, Table } from "sequelize-typescript";
import Address from "./address";
import Product from "./product";

@Table
export default class User extends Model<User> {
    @Column({ type: Sequelize.STRING })
    public firstName: string;

    @Column({ type: Sequelize.STRING })
    public lastName: string;

    @Column
    @ForeignKey(() => Product)
    public productId: number;

    @BelongsTo(() => Product, { foreignKey: "productId" })
    public product: Product;

    @HasMany(() => Address, { foreignKey: "userId" })
    public addresses: Address[] = [];
}
```

```typescript
import { BelongsTo, Column, ForeignKey, Model, Sequelize, Table } from "sequelize-typescript";
import User from "./user";

@Table
export default class Address extends Model<Address> {
    @Column({ type: Sequelize.STRING })
    public type: string;
    @Column({ type: Sequelize.STRING })
    public line1: string;
    @Column({ type: Sequelize.STRING })
    public line2: string;
    @Column({ type: Sequelize.STRING })
    public city: string;
    @Column({ type: Sequelize.STRING })
    public state: string;
    @Column({ type: Sequelize.STRING })
    public zip: string;

    @Column
    @ForeignKey(() => User)
    public userId: number;

    @BelongsTo(() => User, { foreignKey: "userId" })
    public user: User;
}
```

Error, which occurs at `await Product.create<Product>()`:
```
Exception has occurred: EagerLoadingError
EagerLoadingError: Address is not associated to Product!
    at Function._getIncludedAssociation (c:\Dev2\sequelize-typescript-issue-117\node_modules\sequelize\lib\model.js:573:13)
    at Function._validateIncludedElement (c:\Dev2\sequelize-typescript-issue-117\node_modules\sequelize\lib\model.js:489:53)
    at options.include.options.include.map.include (c:\Dev2\sequelize-typescript-issue-117\node_modules\sequelize\lib\model.js:385:37)
    at Array.map (native)
    at Function._validateIncludedElements (c:\Dev2\sequelize-typescript-issue-117\node_modules\sequelize\lib\model.js:381:39)
    at Function.BaseModel.prepareInstantiationOptions (c:\Dev2\sequelize-typescript-issue-117\node_modules\sequelize-typescript\lib\models\BaseModel.js:100:84)
    at Model (c:\Dev2\sequelize-typescript-issue-117\node_modules\sequelize-typescript\lib\models\v4\Model.js:8:45)
    at Product (c:\Dev2\sequelize-typescript-issue-117\src\models\product.ts:16:9)
    at Function.build (c:\Dev2\sequelize-typescript-issue-117\node_modules\sequelize\lib\model.js:1916:12)
    at Function._target.(anonymous function) [as build] (c:\Dev2\sequelize-typescript-issue-117\node_modules\sequelize-typescript\lib\models\BaseModel.js:35:41)
    at Function.create (c:\Dev2\sequelize-typescript-issue-117\node_modules\sequelize\lib\model.js:1967:17)
    at Function._target.(anonymous function) [as create] (c:\Dev2\sequelize-typescript-issue-117\node_modules\sequelize-typescript\lib\models\BaseModel.js:35:41)
    at c:\Dev2\sequelize-typescript-issue-117\src\index.ts:23:26
    at Generator.next (<anonymous>)
    at c:\Dev2\sequelize-typescript-issue-117\src\index.ts:7:71
    at __awaiter (c:\Dev2\sequelize-typescript-issue-117\src\index.ts:3:12)
    at createProduct (c:\Dev2\sequelize-typescript-issue-117\src\index.ts:38:12)
    at c:\Dev2\sequelize-typescript-issue-117\src\index.ts:17:9
    at Generator.next (<anonymous>)
    at fulfilled (c:\Dev2\sequelize-typescript-issue-117\src\index.ts:4:58)
```

How to overcome that correctly?

**Comment by Deilan** [comment]
This :
```typescript
{
    include: [{
        association: User,
        include: [ Address ],
    } as any],
});
```
results the following error:
```
Exception has occurred: TypeError
TypeError: Cannot read property '__origClass' of undefined
    at inferAliasForInclude (c:\Dev2\sequelize-typescript-issue-117\node_modules\sequelize-typescript\lib\services\models.js:248:38)
    at c:\Dev2\sequelize-typescript-issue-117\node_modules\sequelize-typescript\lib\services\models.js:231:19
    at Array.map (native)
    at inferAlias (c:\Dev2\sequelize-typescript-issue-117\node_modules\sequelize-typescript\lib\services\models.js:230:39)
    at inferAliasForInclude (c:\Dev2\sequelize-typescript-issue-117\node_modules\sequelize-typescript\lib\services\models.js:260:19)
    at c:\Dev2\sequelize-typescript-issue-117\node_modules\sequelize-typescript\lib\services\models.js:231:19
    at Array.map (native)
    at Object.inferAlias (c:\Dev2\sequelize-typescript-issue-117\node_modules\sequelize-typescript\lib\services\models.js:230:39)
    at tryPrepareOptions (c:\Dev2\sequelize-typescript-issue-117\node_modules\sequelize-typescript\lib\models\BaseModel.js:76:50)
    at Function._target.(anonymous function) [as create] (c:\Dev2\sequelize-typescript-issue-117\node_modules\sequelize-typescript\lib\models\BaseModel.js:34:21)
    at c:\Dev2\sequelize-typescript-issue-117\src\index.ts:23:26
    at Generator.next (<anonymous>)
    at __awaiter (c:\Dev2\sequelize-typescript-issue-117\src\index.ts:7:71)
    at __awaiter (c:\Dev2\sequelize-typescript-issue-117\src\index.ts:3:12)
    at createProduct (c:\Dev2\sequelize-typescript-issue-117\src\index.ts:38:12)
    at c:\Dev2\sequelize-typescript-issue-117\src\index.ts:17:9
    at Generator.next (<anonymous>)
    at fulfilled (c:\Dev2\sequelize-typescript-issue-117\src\index.ts:4:58)
```

**Comment by Deilan** [comment]
and this:
```typescript
{
    include: [{
        association: (Product as any).User,
        include: [(User as any).Addresses],
    }],
}
```
also won't compile without type assertion (`as any`).
With the assertion it results in the following error:
```
Exception has occurred: TypeError
TypeError: Cannot read property 'model' of undefined
    at inferAliasForInclude (c:\Dev2\sequelize-typescript-issue-117\node_modules\sequelize-typescript\lib\services\models.js:241:51)
    at c:\Dev2\sequelize-typescript-issue-117\node_modules\sequelize-typescript\lib\services\models.js:231:19
    at Array.map (native)
    at inferAlias (c:\Dev2\sequelize-typescript-issue-117\node_modules\sequelize-typescript\lib\services\models.js:230:39)
    at inferAliasForInclude (c:\Dev2\sequelize-typescript-issue-117\node_modules\sequelize-typescript\lib\services\models.js:260:19)
    at c:\Dev2\sequelize-typescript-issue-117\node_modules\sequelize-typescript\lib\services\models.js:231:19
    at Array.map (native)
    at Object.inferAlias (c:\Dev2\sequelize-typescript-issue-117\node_modules\sequelize-typescript\lib\services\models.js:230:39)
    at tryPrepareOptions (c:\Dev2\sequelize-typescript-issue-117\node_modules\sequelize-typescript\lib\models\BaseModel.js:76:50)
    at Function._target.(anonymous function) [as create] (c:\Dev2\sequelize-typescript-issue-117\node_modules\sequelize-typescript\lib\models\BaseModel.js:34:21)
    at c:\Dev2\sequelize-typescript-issue-117\src\index.ts:23:26
    at Generator.next (<anonymous>)
    at __awaiter (c:\Dev2\sequelize-typescript-issue-117\src\index.ts:7:71)
    at __awaiter (c:\Dev2\sequelize-typescript-issue-117\src\index.ts:3:12)
    at createProduct (c:\Dev2\sequelize-typescript-issue-117\src\index.ts:38:12)
    at c:\Dev2\sequelize-typescript-issue-117\src\index.ts:17:9
    at Generator.next (<anonymous>)
    at fulfilled (c:\Dev2\sequelize-typescript-issue-117\src\index.ts:4:58)
```

**Comment by Deilan** [comment]
Seems to me like a public static property should be also defined in the entities to fix that correctly.

**Comment by Deilan** [comment]
```typescript
{
    include: [{
        association: { source: Product, target: User, identifier: "users" },
    }],
}
```
and
```typescript
{
    include: [{
        association: { source: User, target: Product, identifier: "users" },
    }],
}
```
results in the error:
```
Exception has occurred: TypeError
TypeError: instance.set is not a function
    at Promise.map.instance (c:\Dev2\sequelize-typescript-issue-117\node_modules\sequelize\lib\model.js:3652:26)
    at tryCatcher (c:\Dev2\sequelize-typescript-issue-117\node_modules\bluebird\js\release\util.js:16:23)
    at MappingPromiseArray._promiseFulfilled (c:\Dev2\sequelize-typescript-issue-117\node_modules\bluebird\js\release\map.js:61:38)
    at MappingPromiseArray.PromiseArray._iterate (c:\Dev2\sequelize-typescript-issue-117\node_modules\bluebird\js\release\promise_array.js:114:31)
    at MappingPromiseArray.init (c:\Dev2\sequelize-typescript-issue-117\node_modules\bluebird\js\release\promise_array.js:78:10)
    at MappingPromiseArray._asyncInit (c:\Dev2\sequelize-typescript-issue-117\node_modules\bluebird\js\release\map.js:30:10)
    at Async._drainQueue (c:\Dev2\sequelize-typescript-issue-117\node_modules\bluebird\js\release\async.js:138:12)
    at Async._drainQueues (c:\Dev2\sequelize-typescript-issue-117\node_modules\bluebird\js\release\async.js:143:10)
    at Immediate.Async.drainQueues (c:\Dev2\sequelize-typescript-issue-117\node_modules\bluebird\js\release\async.js:17:14)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)
```

**Comment by RobinBuschmann** [comment]
Regarding `EagerLoadingError: Address is not associated to Product!`

As the error says, Address is not associated to Product.

So you need to define the associations in the options correctly:
```typescript
const product = await Product.create<Product>({
        ...
    }, {
        include: [{model: User, include: [Address]}], // <= Address is an include of User, not Product
    });
```

**Comment by RobinBuschmann** [comment]
Regarding

```
{
    include: [{
        association: User,
        include: [ Address ],
    } as any],
});
```
and
```
{
    include: [{
        association: (Product as any).User,
        include: [(User as any).Addresses],
    }],
}
```
Your options do not fulfill the interface. See `IIncludeAssociation` interface:

```typescript
export interface IIncludeAssociation {
    source: typeof Model;
    target: typeof Model;
    identifier: string;
}
```

**Comment by RobinBuschmann** [comment]
I will investigate this error: `Exception has occurred: TypeError
TypeError: instance.set is not a function`

Anyway, I recommend using:
```
include: [{model: User, include: [Address]}]
```

**Comment by Deilan** [comment]
@RobinBuschmann Thanks for the response! The problem with:
```typescript
include: [{model: User, include: [Address]}]
```
is that `User` and `Address` objects are not inserted as result, only `Product` object is inserted.

**Comment by RobinBuschmann** [comment]
Ah ok, I see. This is because you named the `User` array in the `Product` class `public`:

```typescript
@Table
export default class Product extends Model<Product> {
    @HasMany(() => User, { foreignKey: "productId" })
    public public: User[] = []; // <= I'm assuming that this is a typo and it should be 'users' 
}
```

Additionally you are using an object while creating the user relation, but the relations expects an array:

```typescript
user: { // <=
            first_name: "Mick",
            last_name: "Broadstone",
            addresses: [{
                type: "home",
                line_1: "100 Main St.",
                city: "Austin",
                state: "TX",
                zip: "78704",
            }],
        },
``` 
Define it like so:
```typescript
```typescript
users: [{ // <=
            first_name: "Mick",
            last_name: "Broadstone",
            addresses: [{
                type: "home",
                line_1: "100 Main St.",
                city: "Austin",
                state: "TX",
                zip: "78704",
            }],
        }],
``` 
```

**Comment by Deilan** [comment]
Sorry, I fixed the typo in my code and forgot to update the snippets.

And you're totally right about `users` object: the problem was because of inconsistency with usage of array/object.

Thank you very much!

I also strongly recommend to include the solution we've come up to (`include: [{model: User, include: [Address]}]`) to the docs!

**Comment by RobinBuschmann** [comment]
Hey @Deilan, this should already be a part of the sequelize docs.

Can I close this issue now? :)

**Comment by Deilan** [comment]
@RobinBuschmann Unfortunately it's not a part of the sequelize docs. :)

I think it would be very helpful if it will be in `sequelize-typescript`'s docs as far as we already found the solution. But it's completely up to you of course. :)

**Comment by nomanbiniqbal** [comment]
Issue in creation i have simple two models 
`export default class Tenant extends Model<TenantDto, CreateTenantDto> implements TenantDto {
 @ForeignKey(() => SupportCoordinator)
  @Column
  public support_coordinator_id: number;
  @Expose()
  @BelongsTo(() => SupportCoordinator)
  public supportCoordinator: SupportCoordinator;
}


@Exclude()
@Table({
  modelName: 'support_coordinator'
})
export default class SupportCoordinator
  extends Model<SupportCoordinatorDto, CreateSupportCoordinatorDto>
  implements SupportCoordinatorDto {

  @Column({ primaryKey: true, type: DataType.INTEGER, autoIncrement: true })
  public id: number;

  @Expose()
  @Column
  public name: string;
  @Expose()
  @Column
  public contact: string;

  @HasOne(() => Tenant, 'support_coordinator_id')
  public tenant: Tenant;
};

`

**Comment by agrofcsik** [comment]
Does anyone know of `sequelize-typescript` model examples where the column names of two tables aren't the same name. I'm dealing with a legacy table where the original architect didn't do that. The example is: `User table` (userId, firstName, lastName, **deptCode**) and the `Department table` is (**deptId**, name) where deptCode = deptId. I need to get the department info for a user, but also get a list of users in the department. There is no lookup table in between either.

**Comment by lukashroch** [comment]
@agrofcsik you can pass object, where you can define further options ( instead of a foreignKey string.)

It should something like this:
```ts
@HasOne(() => Tenant, {
    foreignKey: 'deptId',
    sourceKey: 'deptCode',
})
```

**Comment by agrofcsik** [comment]
@[lukashroch](https://github.com/lukashroch) Thanks, now I'm running into a `Cyclic dependency` I believe because I have a `@HasOne(() => Department)` in User and a `@HasMany(() => User, {` in Department. Not sure how to squash that.

**Comment by agrofcsik** [comment]
So for tables that have a relationship but don't have matching keys..I ended up with...

In the User: 
[@BelongsTo(() => Department, {
    foreignKey: 'deptCode',
    targetKey: 'deptId'
})](url)

In the Department:
```
@HasMany(() => User, {
    foreignKey: 'deptCode',
    sourceKey: 'deptId'
})
```

This allowed for:
GetUserWithDeptInfo():
```
const deptInfo = await User.scope(req.query['scope']?.toString()).findOne({
      where: {
        userId: req.params['id']
      },
      include: [Department],
});
```

And GetDeptUsers():
```
const deptUsers = await Department.findOne({ include: [User] }).then((dept) => {
       dept?.users?.forEach((user) => console.log(`User ${user.firstName}`))
})
```

If it helps anyone..
