### ISSUE TITLE
TypeError: definedModel.initialize is not a function

### ISSUE THREAD

**Issue by DmitryKamynin** [RobinBuschmann/sequelize-typescript#1215]
# Issue

## Versions

- sequelize: 6.16.1
- sequelize-typescript: 2.1.3
- typescript: 4.5.5

## Issue type

- [x] bug report
- [ ] feature request

## Actual behavior

I get an error when I try to run my project, I don't have this problem with regular sequelize, but using your decorators is too tempting, so I ask you to help me find the problem, I suspect that I just stumbled upon it, but I did not find a solution on the Internet

```ts
const sequelize = new Sequelize({
  database: process.env.DB_NAME,
  password: process.env.DB_PASSWORD,
  host: process.env.HOST_NAME,
  username: process.env.DB_USERNAME,
  dialect: "postgres",
  models: [__dirname + "/api/**/model/*.ts"],
});
```

## my tsconfig
```ts
{
  "ts-node": {
    "files": true
  },
  "include": [
    "src",
    "types/*.d.ts"
  ],
  "compilerOptions": {
    "target": "es6",
    "experimentalDecorators": true,
    "emitDecoratorMetadata": true,
    "module": "commonjs",
    "resolveJsonModule": true,
    "outDir": "dist",
    "allowJs": true,
    "checkJs": true,
    "isolatedModules": true,
    "allowSyntheticDefaultImports": true,
    "esModuleInterop": true,
    "forceConsistentCasingInFileNames": true,
    "skipLibCheck": true
  }
}
```

```
TypeError: definedModel.initialize is not a function
    at D:\pet projects\Giftouch\node_modules\sequelize-typescript\dist\sequelize\sequelize\sequelize.js:73:26
    at Array.map (<anonymous>)
    at Sequelize.defineModels (D:\pet projects\Giftouch\node_modules\sequelize-typescript\dist\sequelize\sequelize\sequelize.js:61:23)
    at Sequelize.addModels (D:\pet projects\Giftouch\node_modules\sequelize-typescript\dist\sequelize\sequelize\sequelize.js:37:36)
    at Object.<anonymous> (D:\pet projects\Giftouch\src\api\modules\Product\model\Product.ts:25:11)
    at Module._compile (node:internal/modules/cjs/loader:1097:14)
    at Module._compile (D:\pet projects\Giftouch\node_modules\source-map-support\source-map-support.js:568:25)
    at Module.m._compile (C:\Users\dmitry\AppData\Local\Temp\ts-node-dev-hook-4742013169399544.js:69:33)
    at Module._extensions..js (node:internal/modules/cjs/loader:1149:10)
    at require.extensions..jsx.require.extensions..js (C:\Users\dmitry\AppData\Local\Temp\ts-node-dev-hook-4742013169399544.js:114:20)
[ERROR] 10:28:24 TypeError: definedModel.initialize is not a function
```

**Comment by VahanMargaryan** [comment]
hey,
the problem comes from importing Model from "sequelize" instead of "sequelize-typescript"

`import { Model } from "sequelize-typescript";`

**Comment by DmitryKamynin** [comment]
what a mess... thanks for the help!
