### ISSUE TITLE
Class constructor [ClassName] cannot be invoked without 'new'

### ISSUE THREAD

**Issue by ibox4real** [RobinBuschmann/sequelize-typescript#138]
I get an error when querying the User model

Error
```json
{
name: "TypeError",
message: "Class constructor User cannot be invoked without 'new'",
stack: "TypeError: Class constructor User cannot be invoked without 'new' at _loop_1 (/opt/auth/node_modules/class-transformer/TransformOperationExecutor.js:108:47) at TransformOperationExecutor.transform (/opt/auth/node_modules/class-transformer/TransformOperationExecutor.js:172:17) at _loop_1 (/opt/auth/node_modules/class-transformer/TransformOperationExecutor.js:148:45) at TransformOperationExecutor.transform (/opt/auth/node_modules/class-transformer/TransformOperationExecutor.js:172:17) at _loop_1 (/opt/auth/node_modules/class-transformer/TransformOperationExecutor.js:148:45) at TransformOperationExecutor.transform (/opt/auth/node_modules/class-transformer/TransformOperationExecutor.js:172:17) at _loop_1 (/opt/auth/node_modules/class-transformer/TransformOperationExecutor.js:148:45) at TransformOperationExecutor.transform (/opt/auth/node_modules/class-transformer/TransformOperationExecutor.js:172:17) at _loop_1 (/opt/auth/node_modules/class-transformer/TransformOperationExecutor.js:148:45) at TransformOperationExecutor.transform (/opt/auth/node_modules/class-transformer/TransformOperationExecutor.js:172:17) at ClassTransformer.classToPlain (/opt/auth/node_modules/class-transformer/ClassTransformer.js:9:25) at Object.classToPlain (/opt/auth/node_modules/class-transformer/index.js:12:29) at ExpressDriver.handleSuccess (/opt/auth/node_modules/routing-controllers/driver/express/ExpressDriver.js:207:42) at /opt/auth/node_modules/routing-controllers/RoutingControllers.js:128:61 at <anonymous>"
}
```

node:8
```
"sequelize": "^4.8.4",
"sequelize-typescript": "^0.5.0",
"typescript": "^2.5.2"
```

tsconfig 
```json
{
  "compilerOptions": {
    "baseUrl": ".",
    "module": "commonjs",
    "noImplicitReturns": true,
    "noImplicitThis": true,
    "noUnusedLocals": true,
    "preserveConstEnums": true,
    "removeComments": true,
    "strictNullChecks": true,
    "target": "es6",
    "rootDir": "src/",
    "outDir": "dist/src",
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true
  },
  "include": [
    "./src/**/*"
  ]
}
```
User model
```javascript
import { Table, Column, PrimaryKey, AutoIncrement, DataType, Model, UpdatedAt, CreatedAt } from 'sequelize-typescript';

@Table({
    tableName: 'user'
})
export default class User extends Model<User> {

    @PrimaryKey
    @AutoIncrement
    @Column
    id: number;

    @Column({
        type: DataType.STRING(255),
        unique: true
    })
    email: string;

    @Column({
        type: DataType.STRING(15),
        allowNull: true
    })
    phone_number: string;

    @Column({
        type: DataType.STRING(45),
        allowNull: true
    })
    first_name: string;
    @Column({
        type: DataType.STRING(45),
        allowNull: true
    })
    last_name: string;

    @Column({
        type: DataType.STRING(64)
    })
    password: string;

    @CreatedAt
    created_at: string;

    @UpdatedAt
    updated_at: string;
}
```

**Comment by RobinBuschmann** [comment]
Hey @ibox4real, this is an issue with `class-transfromer`. It tries to invoke a class constructor without the `new` keyword. Same as https://github.com/RobinBuschmann/sequelize-typescript/issues/123#issuecomment-328643178

This should be reported to `class-transformer` instead :)

**Comment by ibox4real** [comment]
Thank you, it seems the  best option is to disable classTranformers in the @pleerock/routing-controllers setup.

**Comment by doovers** [comment]
@ibox4real How did you disable classTransformers?

**Comment by ibox4real** [comment]
I'm using  pleerock/routing-controllers which uses pleerock/class-transformer
To disable classTransformer you need to specify a { classTransformer: false } in RoutingControllerOptions when creating a server.

**Comment by doovers** [comment]
@ibox4real Not sure how I can do something similar with my setup but thanks for the response!

**Comment by MikeDabrowski** [comment]
@ibox4real Huge thanks! I also use routing-controllers. Finally I was able to create many to many and got the exact problem you had here. What will I loose by disabling class-transformer, and maybe I can do this without disabling it (perhaps moving my sequelize-ts code somewhere else)?

**Comment by stormit-vn** [comment]
Hi,

I am facing this issue, it will works if we set target to es6, but when setting target to es6, the sequelize transaction will not working anymore. Does anyone know how to fix this issue without changing target or how to make transaction works with es6?

Thanks in advance!
