### ISSUE TITLE
Testing models

### ISSUE THREAD

**Issue by ibox4real** [RobinBuschmann/sequelize-typescript#171]
Is there a simple way to test the models in isolation? 

If i run this i get an exception 
```
import { expect } from 'chai';
import User from 'src/common/models/user';

describe("User", () => {
    it ('should return true on password verification', () => {
        const password = 'secret';
        const user = new User({
            email: 'john@doe.com',
            pasword: password
        });
        expect(user.verifyPassword(password)).to.equal(true);
    })
})
```

```
TypeError: Cannot read property 'createdAt' of undefined
      at User._initValues (node_modules/sequelize/lib/model.js:3009:48)
      at User.Model (node_modules/sequelize/lib/model.js:2983:10)
      at Model (node_modules/sequelize-typescript/lib/models/v4/Model.js:8:9)
      at User (src/common/models/user.ts:11:1)
      at Context.it (test/unit/common/models/user.spec.ts:10:22)
```

I guess its because the connection was not initialized. Any advice on how to get around this?

**Comment by RobinBuschmann** [comment]
The Models need to be initialized, but if you don't want them to be connected to a database, you can create a validation-only `Sequelize` instance like so:

```typescript
import {Sequelize} from 'sequelize-typescript';

const sequelize = new Sequelize({validateOnly: true});
sequelize.addModels([User]);

// or
const sequelize = new Sequelize({
  validateOnly: true,
  modelPaths: [__dirname + 'path/to/your/models']
});

const user = new User({
    email: 'john@doe.com',
    pasword: password
});

user.verify...
``` 

(The error message is not really helpful, I know - this will be fixed soon)

**Comment by ibox4real** [comment]
This will suffice, thank you!
