### ISSUE TITLE
@Table annotation is missing on class ...

### ISSUE THREAD

**Issue by SaadiKarim** [RobinBuschmann/sequelize-typescript#178]
Hi,
An error is thrown on the creation of my Sequelize instance.
I'm using the `modelPaths: [__dirname + '/../models/']` way 
and for some reason it says that the @Table annotation is missing on the first model of the folder...

Here's a code sample 
`import {
  AutoIncrement, Column, CreatedAt, DataType, Model,PrimaryKey, Table, UpdatedAt
} from "sequelize-typescript";`

`@Table({
  modelName: "Booking",
  tableName: "bookings"
})`

`export default class Booking extends Model<Booking>{}`

EDIT : 
the sequelize instantiation 
`this.sequelize = new Sequelize({
        name: '***',
        dialect: 'mysql',
        host: 'localhost',
        username: 'root',
        password: '',
        modelPaths: [__dirname + '/../models/']
      });`

Any idea? I'm surely doing something wrong but i can't figure it...

**Comment by SaadiKarim** [comment]
Hi again,
I may have something. I work on a Sails.js project, and for some reasons one of my coworker required a model on a Sails.js pocily like so
`let UserModel = require("../models/UserModel");`

If I remove this line everything works fine.
Is there a reason why we shouldn't require models ?

Thx

**Comment by RobinBuschmann** [comment]
Hey @SaadiKarim can you provide the full error message including the stack trace?

**Comment by SaadiKarim** [comment]
Yep here it is
`Error: @Table annotation is missing on class "BookingModel"
    at OriginSequelize.defineModels.models.forEach.model (c:\dossin-booking-api\node_modules\sequelize-typescript\lib\models\v4\Sequelize.js:53:23)
    at Array.forEach (native)
    at Sequelize.defineModels (c:\dossin-booking-api\node_modules\sequelize-typescript\lib\models\v4\Sequelize.js:48:16)
    at Sequelize.BaseSequelize.addModels (c:\dossin-booking-api\node_modules\sequelize-typescript\lib\models\BaseSequelize.js:60:14)
    at Object.login [as user/login] (c:\dossin-booking-api\api\controllers\UserController.ts:35:13)
    at c:\dossin-booking-api\node_modules\sails\lib\router\bind.js:246:46
    at routeTargetFnWrapper (c:\dossin-booking-api\node_modules\sails\lib\router\bind.js:390:9)
    at Layer.handle [as handle_request] (c:\dossin-booking-api\node_modules\express\lib\router\layer.js:95:5)
    at next (c:\dossin-booking-api\node_modules\express\lib\router\route.js:137:13)
    at Route.dispatch (c:\dossin-booking-api\node_modules\express\lib\router\route.js:112:3)
    at Layer.handle [as handle_request] (c:\dossin-booking-api\node_modules\express\lib\router\layer.js:95:5)
    at c:\dossin-booking-api\node_modules\express\lib\router\index.js:281:22
    at Function.process_params (c:\dossin-booking-api\node_modules\express\lib\router\index.js:335:12)
    at next (c:\dossin-booking-api\node_modules\express\lib\router\index.js:275:10)
    at next (c:\dossin-booking-api\node_modules\express\lib\router\route.js:127:14)
    at isLoggedIn (c:\dossin-booking-api\api\policies\hydrateValues.js:9:10)
    at routeTargetFnWrapper (c:\dossin-booking-api\node_modules\sails\lib\router\bind.js:390:9)
    at Layer.handle [as handle_request] (c:\dossin-booking-api\node_modules\express\lib\router\layer.js:95:5)
    at next (c:\dossin-booking-api\node_modules\express\lib\router\route.js:137:13)
    at Route.dispatch (c:\dossin-booking-api\node_modules\express\lib\router\route.js:112:3)
    at Layer.handle [as handle_request] (c:\dossin-booking-api\node_modules\express\lib\router\layer.js:95:5)
    at c:\dossin-booking-api\node_modules\express\lib\router\index.js:281:22
    at Function.process_params (c:\dossin-booking-api\node_modules\express\lib\router\index.js:335:12)
    at next (c:\dossin-booking-api\node_modules\express\lib\router\index.js:275:10)
    at next (c:\dossin-booking-api\node_modules\express\lib\router\route.js:127:14)
    at Hook.expressMiddleware (c:\dossin-booking-api\node_modules\sails\lib\hooks\i18n\index.js:202:14)
at Hook.wrapper [as expressMiddleware] (c:\dossin-booking-api\node_modules\@sailshq\lodash\lib\index.js:3250:19)
    at addLocalizationMethod (c:\dossin-booking-api\node_modules\sails\lib\hooks\i18n\index.js:147:35)
    at routeTargetFnWrapper (c:\dossin-booking-api\node_modules\sails\lib\router\bind.js:390:9)
    at Layer.handle [as handle_request] (c:\dossin-booking-api\node_modules\express\lib\router\layer.js:95:5)
    at next (c:\dossin-booking-api\node_modules\express\lib\router\route.js:137:13)
    at Route.dispatch (c:\dossin-booking-api\node_modules\express\lib\router\route.js:112:3)
    at Layer.handle [as handle_request] (c:\dossin-booking-api\node_modules\express\lib\router\layer.js:95:5)
    at c:\dossin-booking-api\node_modules\express\lib\router\index.js:281:22
    at param (c:\dossin-booking-api\node_modules\express\lib\router\index.js:354:14)
    at param (c:\dossin-booking-api\node_modules\express\lib\router\index.js:365:14)
    at Function.process_params (c:\dossin-booking-api\node_modules\express\lib\router\index.js:410:3)
    at next (c:\dossin-booking-api\node_modules\express\lib\router\index.js:275:10)
    at next (c:\dossin-booking-api\node_modules\express\lib\router\route.js:127:14)
    at module.exports.sails.on.sails.router.bind._middlewareType (c:\dossin-booking-api\node_modules\sails\lib\hooks\security\csrf\index.js:92:20)
    at routeTargetFnWrapper (c:\dossin-booking-api\node_modules\sails\lib\router\bind.js:390:9)
    at Layer.handle [as handle_request] (c:\dossin-booking-api\node_modules\express\lib\router\layer.js:95:5)
    at next (c:\dossin-booking-api\node_modules\express\lib\router\route.js:137:13)
    at Route.dispatch (c:\dossin-booking-api\node_modules\express\lib\router\route.js:112:3)
    at Layer.handle [as handle_request] (c:\dossin-booking-api\node_modules\express\lib\router\layer.js:95:5)
    at c:\dossin-booking-api\node_modules\express\lib\router\index.js:281:22
    at param (c:\dossin-booking-api\node_modules\express\lib\router\index.js:354:14)
    at param (c:\dossin-booking-api\node_modules\express\lib\router\index.js:365:14)
    at Function.process_params (c:\dossin-booking-api\node_modules\express\lib\router\index.js:410:3)
    at next (c:\dossin-booking-api\node_modules\express\lib\router\index.js:275:10)
    at next (c:\dossin-booking-api\node_modules\express\lib\router\route.js:127:14)
    at clearCSRFTokenLocal (c:\dossin-booking-api\node_modules\sails\lib\hooks\security\csrf\index.js:79:16)`

**Comment by SaadiKarim** [comment]
Well this is getting crazy...when I rename my file Booking Class file "UserA.ts" it works, but as soon as I give it it's original name ('Booking.ts') the 'Annotion Missing' occures...could this have something to do with the TS transpilation ?

**Comment by RobinBuschmann** [comment]
Do you have an example repo where I can have a look at?

**Comment by RobinBuschmann** [comment]
@SaadiKarim Do you still have this issue or can this be closed now?

**Comment by SaadiKarim** [comment]
I'm sorry I didn't reply sooner. We manage to get rid of this error but I have absolutly no clue how. It just worked. You can close the issue. Sorry again for the late reply

**Comment by RobinBuschmann** [comment]
Thanks for the response :)

**Comment by TalissonJunior** [comment]
Hi,
I don´t know why but i´m having the same issue;

It´s really weird because after i transpile the same code 3 times without changing anything from it i got the same error:
```
 @Table annotation is missing on class "ExampleEmployee"
```


Here's my model code sample
https://github.com/TalissonJunior/NodeExpressWebApi/blob/master/src/Models/Database/ExampleEmployee.ts#L4

the sequelize instantiation:
https://github.com/TalissonJunior/NodeExpressWebApi/blob/master/src/server.ts#L38

Any idea? is this really a random error? because sometimes works and sometimes don´t.
Here is a  full error message including the stack trace:
```

D:\Users\p066871\Desktop\testes\NodeExpressWebApi\node_modules\sequelize-typescript\lib\models\v4\Sequelize.js:53
                throw new Error(`@Table annotation is missing on class "${model['name']}"`);
                ^

Error: @Table annotation is missing on class "ExampleEmployee"
    at models.forEach.model (D:\Users\p066871\Desktop\testes\NodeExpressWebApi\node_modules\sequelize-typescript\lib\models\v4\Sequelize.js:53:23)
    at Array.forEach (<anonymous>)
    at Sequelize.defineModels (D:\Users\p066871\Desktop\testes\NodeExpressWebApi\node_modules\sequelize-typescript\lib\models\v4\Sequelize.js:48:16)
    at Sequelize.BaseSequelize.addModels (D:\Users\p066871\Desktop\testes\NodeExpressWebApi\node_modules\sequelize-typescript\lib\models\BaseSequelize.js:60:14)
    at Sequelize.BaseSequelize.init (D:\Users\p066871\Desktop\testes\NodeExpressWebApi\node_modules\sequelize-typescript\lib\models\BaseSequelize.js:69:18)
    at new Sequelize (D:\Users\p066871\Desktop\testes\NodeExpressWebApi\node_modules\sequelize-typescript\lib\models\v4\Sequelize.js:29:18)
    at Server.config (D:\Users\p066871\Desktop\testes\NodeExpressWebApi\build\server.js:30:9)
    at new Server (D:\Users\p066871\Desktop\testes\NodeExpressWebApi\build\server.js:23:14)
    at Object.<anonymous> (D:\Users\p066871\Desktop\testes\NodeExpressWebApi\build\server.js:75:19)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (D:\Users\p066871\Desktop\testes\NodeExpressWebApi\build\index.js:5:18)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3) ```

And if you want to test you can clone the repo:
https://github.com/TalissonJunior/NodeExpressWebApi
```

and then:

```npm install && gulp serve ```
