### ISSUE TITLE
Compiling dependant JS results in "cannot find module" error

### ISSUE THREAD

**Issue by damianb** [RobinBuschmann/sequelize-typescript#220]
When running tsc to compile my application's typescript, I get the following error:

```
$ npm run build && npm start

> myapp@0.0.0 build myapp
> tsc


> myapp@0.0.0 start myapp
> node build/app

module.js:538
    throw err;
    ^

Error: Cannot find module 'reflect-metadata'
    at Function.Module._resolveFilename (module.js:536:15)
    at Function.Module._load (module.js:466:25)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (myapp\node_modules\sequelize-typescript\lib\annotations\AutoIncrement.js:3:1)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)

```

I noted that this is in the devDependencies, but not the dependencies array.

```
$ node --version
v8.9.0
$ npm ls | grep typescript
+-- sequelize-typescript@0.6.1
`-- typescript@2.6.2
$ npm ls | grep sequelize
+-- sequelize@4.26.0
+-- sequelize-typescript@0.6.1
| +-- @types/sequelize@4.0.79
$ npm ls | grep reflect-metadata
| +-- @types/reflect-metadata@0.0.4
$ cat tsconfig.json
{
	"compilerOptions": {
		"alwaysStrict": true,
		"declaration": true,
		"declarationDir": "./build/",
		"module": "commonjs",
		"moduleResolution": "node",
		"noImplicitAny": true,
		"noImplicitReturns": true,
		"outDir": "./build",
		"sourceMap": true,
		"strictNullChecks": true,
		"experimentalDecorators": true,
		"target": "ES2017"
	},
	"include": [
		"./src/**/*"
	]
}
```

**Comment by RobinBuschmann** [comment]
Hey @damianb, you need to install `reflect-metadata` manually.

**Comment by damianb** [comment]
Ahhh, gotcha - why no peerDependencies? I see you described something in #8, but that sounds like an NPM bug, honestly.
