### ISSUE TITLE
Cannot read property 'createdAt' of undefined

### ISSUE THREAD

**Issue by ReneHollander** [RobinBuschmann/sequelize-typescript#296]
I am trying to use sequelize-typescript instead of MongoDB in [Angular-Full-Stack](https://github.com/DavideViolante/Angular-Full-Stack). They already provide multiple tsconfigs. I only added `"target": "es6"` to the config in `server/` because I am using sequelize v4, but I am always getting the following error:
```
[2] Fri, 09 Feb 2018 13:40:11 GMT sequelize deprecated String based operators are now deprecated. Please use Symbol based operators for better security, read more at http://docs.sequelizejs.com/manual/tutorial/querying.html#operators at node_modules\sequelize\lib\sequelize.js:242:13
[2] Executing (default): SELECT 1+1 AS result
[2] TypeError: Cannot read property 'createdAt' of undefined
[2]     at User._initValues (C:\Users\Rene Hollander\repositories\ibex\node_modules\sequelize\lib\model.js:3082:49)
[2]     at new Model (C:\Users\Rene Hollander\repositories\ibex\node_modules\sequelize\lib\model.js:3056:10)
[2]     at new Model (C:\Users\Rene Hollander\repositories\ibex\node_modules\sequelize-typescript\lib\models\v4\Model.js:8:9)
[2]     at new User (C:\Users\Rene Hollander\repositories\ibex\dist\server\models\user.model.js:23:12)
[2]     at C:\Users\Rene Hollander\repositories\ibex\dist\server\app.js:45:20
[2]     at Generator.next (<anonymous>)
[2]     at fulfilled (C:\Users\Rene Hollander\repositories\ibex\dist\server\app.js:4:58)
[2]     at <anonymous>
```

Running it directly with `node --inspect --require ts-node/register app.ts` with `server/` as the working directory is working as expected. So I am assuming that one config option they add breaks sequelize-typescript.

I pushed my current code with the compiled files to a test repository: https://github.com/ReneHollander/sequelize-not-working
Running with `npm run dev` should show the error.

**Comment by RobinBuschmann** [comment]
Hey @ReneHollander the following line causes the issue: https://github.com/ReneHollander/sequelize-not-working/blob/master/server/app.ts#L32

Since you're compiling your source files first and running the application afterwards, there are no ts files any more in your `dist/server/models` folder. That means the `User` model is never initialized. So you need to change the glob to `/models/*.model.js`.

`/models/*.model.ts` will only work when running your application with [ts-node](https://www.npmjs.com/package/ts-node)

**Comment by ReneHollander** [comment]
Ah yes, that makes sense. It is now working es expected!
Thank you!
