### ISSUE TITLE
Cannot read property 'hasOwnProperty' of undefined

### ISSUE THREAD

**Issue by rochapablo** [RobinBuschmann/sequelize-typescript#307]
When I try to run on Heroku I got:

```
2018-02-16T20:55:15.987519+00:00 app[web.1]: TypeError: Cannot read property 'hasOwnProperty' of undefined
2018-02-16T20:55:15.987521+00:00 app[web.1]:     at Function.BaseSequelize.isISequelizeUriConfig (/app/node_modules/sequelize-typescript/lib/models/BaseSequelize.js:32:19)
2018-02-16T20:55:15.987523+00:00 app[web.1]:     at Sequelize (/app/node_modules/sequelize-typescript/lib/models/v4/Sequelize.js:20:48)
2018-02-16T20:55:15.987524+00:00 app[web.1]:     at Object.<anonymous> (/app/dist/config/sequelize.js:7:19)
2018-02-16T20:55:15.987526+00:00 app[web.1]:     at Module._compile (module.js:573:30)
2018-02-16T20:55:15.987528+00:00 app[web.1]:     at Object.Module._extensions..js (module.js:584:10)
2018-02-16T20:55:15.987529+00:00 app[web.1]:     at Module.load (module.js:507:32)
2018-02-16T20:55:15.987531+00:00 app[web.1]:     at tryModuleLoad (module.js:470:12)
2018-02-16T20:55:15.987533+00:00 app[web.1]:     at Function.Module._load (module.js:462:3)
2018-02-16T20:55:15.987534+00:00 app[web.1]:     at Module.require (module.js:517:17)
2018-02-16T20:55:15.987536+00:00 app[web.1]:     at require (internal/module.js:11:18)
2018-02-16T20:55:15.987538+00:00 app[web.1]:     at Object.<anonymous> (/app/dist/app.js:30:21)
2018-02-16T20:55:15.987540+00:00 app[web.1]:     at Module._compile (module.js:573:30)
2018-02-16T20:55:15.987542+00:00 app[web.1]:     at Object.Module._extensions..js (module.js:584:10)
2018-02-16T20:55:15.987543+00:00 app[web.1]:     at Module.load (module.js:507:32)
2018-02-16T20:55:15.987545+00:00 app[web.1]:     at tryModuleLoad (module.js:470:12)
2018-02-16T20:55:15.987546+00:00 app[web.1]:     at Function.Module._load (module.js:462:3)
2018-02-16T20:55:15.987548+00:00 app[web.1]:     at Module.require (module.js:517:17)
2018-02-16T20:55:15.987549+00:00 app[web.1]:     at require (internal/module.js:11:18)
2018-02-16T20:55:15.987551+00:00 app[web.1]:     at Object.<anonymous> (/app/dist/server.js:3:13)
2018-02-16T20:55:15.987553+00:00 app[web.1]:     at Module._compile (module.js:573:30)
2018-02-16T20:55:15.987555+00:00 app[web.1]:     at Object.Module._extensions..js (module.js:584:10)
2018-02-16T20:55:15.987556+00:00 app[web.1]:     at Module.load (module.js:507:32)
```

Running locally it's all working.

```
"sequelize": "^4.33.2",
"sequelize-typescript": "^0.6.2",
```

**Comment by rochapablo** [comment]
Oops, sorry! I wasn't setting the right environment.
