### ISSUE TITLE
'isInitialized' of undefined association problem.

### ISSUE THREAD

**Issue by aasmm7x** [RobinBuschmann/sequelize-typescript#357]
Looks like when we try to put an association of model B.model.ts on an A.model.ts results in the following error:

`TypeError: Cannot read property 'isInitialized' of undefined`

```
/node_modules/sequelize-typescript/lib/models/association/BaseAssociation.js:19
        if (!modelClass.isInitialized) {
                        ^
TypeError: Cannot read property 'isInitialized' of undefined
    at BelongsToAssociation.BaseAssociation.getAssociatedClass (/node_modules/sequelize-typescript/lib/models/association/BaseAssociation.js:19:25)
```

The file os model names must be ordered by his association as well ?

**Comment by RobinBuschmann** [comment]
@aasmm7x Do you still have this issue?

**Comment by skshrivas** [comment]
Hi @RobinBuschmann 
I am having same issue , i have to model class -
1) In Questions.ts --
```
 @AllowNull(false)
    @ForeignKey(() => Options)
    @Column({
      unique: true,
    })
    public optionId: number;
  
    @BelongsTo(() => Options)
    public options: Options;
```
**and  2) in Options.ts**
```
 @AllowNull(false)
    @ForeignKey(() => Question)
    @Column({
      unique: true,
    })
    public questionId: number;

    @HasOne(() => Question)
    question: Question;
   
```

when i am starting me server getting error as below -
\node_modules\sequelize-typescript\lib\models\association\BaseAssociation.js:19
        if (!modelClass.isInitialized) {
                       ^

TypeError: Cannot read property 'isInitialized' of undefined
    at HasAssociation.BaseAssociation.getAssociatedClass (E:\A_TS_WS\Exceed\node_modules\sequelize-typescript\lib\models\association\BaseAssociation.js:19:24)
    at HasAssociation.getPreparedOptions (E:\A_TS_WS\Exceed\node_modules\sequelize-typescript\lib\models\association\HasAssociation.js:35:36)
    at HasAssociation.BaseAssociation.init (E:\A_TS_WS\Exceed\node_modules\sequelize-typescript\lib\models\association\BaseAssociation.js:28:34)
    at E:\A_TS_WS\Exceed\node_modules\sequelize-typescript\lib\models\BaseSequelize.js:81:29
    at Array.forEach (native)
    at E:\A_TS_WS\Exceed\node_modules\sequelize-typescript\lib\models\BaseSequelize.js:80:26
    at Array.forEach (native)
    at Sequelize.BaseSequelize.associateModels (E:\A_TS_WS\Exceed\node_modules\sequelize-typescript\lib\models\BaseSequelize.js:76:16)
    at Sequelize.BaseSequelize.addModels (E:\A_TS_WS\Exceed\node_modules\sequelize-typescript\lib\models\BaseSequelize.js:62:14)
    at Object.<anonymous> (E:\A_TS_WS\Exceed\server\models\Options.js:70:20)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)

**Comment by RobinBuschmann** [comment]
@skshrivas Unfortunately I cannot reproduce the issue. Can you provide an example repo please?

**Comment by Mreddi1** [comment]
@aasm-moura use:

> export **default** class

**Comment by eboswort** [comment]
I just ran into the same issue. Thanks @Mreddi1 for pointing me in the right direction. I just want to add a little info for the next person who comes here looking for answers. In my case I was importing the association via `import { AssociatedModel } from "../models"` where models is a module that imports and reexports all my models. The fix for me was to use `import { AssociatedModel } from "./AssociatedModel"`. Guess it's something about the indirect import?

**Comment by programmerkgit** [comment]
I just ran into the same issue.

**Comment by programmerkgit** [comment]
I solved The Problem.

Associated Models should be Added To Models at the same time.

It Will Not Work.
`sequelize.addModels([ Options]);
 sequelize.addModels([ Question ]);
`

It Will Work
`sequelize.addModels([ Options, Question ]);`

And re export Options, And Question from the file which is 'sequelize.addModels' is called so that models be initialized before imported.

**Comment by vipulpatel1994** [comment]
Not solving my problem still facing same issue

**Comment by RobinBuschmann** [comment]
@vipulpatel1994 Can you create a new issue with a description of your very problem?

**Comment by vipulpatel1994** [comment]
Sure 
https://github.com/RobinBuschmann/sequelize-typescript/issues/562

**Comment by RoelRoel** [comment]
The errorhandling could be better. A wrong import caused my problem.

**Comment by dianjuar** [comment]
WHAT AN ISSUE!
Thanks @eboswort! You were absolutely right!

I'm going to expose my problem to future developers.

---
A module needed other modules

This is wrong ❌
```ts
import { BoundaryModel, CropModel, FieldModel, SeasonModel } from '..';
```

This is right ✔️
```ts
import BoundaryModel from '../boundary/boundary.model';
import CropModel from '../crop/crop.model';
import FieldModel from '../field/field.model';
import SeasonModel from '../season/season.model';
```

----

You can not import models using a module that re-exports those models, I don't know why

**Comment by amanprince28** [comment]
I am getting the same error, followed all the solutions.
question.model.ts
```
import { Column, Table, PrimaryKey, Default, DataType } from "sequelize-typescript";
import { Model } from "sequelize/types";

@Table({timestamps: true})
export class Questions extends Model<Questions> {

    @PrimaryKey
    @Default(DataType.UUIDV1)
    @Column(DataType.UUID)
    id: string;

    @Column
    question: string;

    @Column({ defaultValue: true })
    isActive: boolean;
}
```
options.model.ts
```
import { Column, Table, PrimaryKey, Default, DataType, ForeignKey, HasOne } from "sequelize-typescript";
import { Model } from "sequelize/types";
import { Questions } from "./models/questions.model";

@Table({timestamps: true})
export class Options extends Model<Options> {

    @PrimaryKey
    @Default(DataType.UUIDV1)
    @Column(DataType.UUID)
    id: string;

    @ForeignKey(() => Questions)
    @Column
    questionsId: number;

    @HasOne(() => Questions)
    question: Questions;

    @Column({ defaultValue: false })
    isCorrectAns: boolean;
}
```
my user module
```
import { SequelizeModule } from '@nestjs/sequelize';
import { Questions } from './models/questions.model';
import { Options } from './options.model';

@Module({
  imports: [
    SequelizeModule.forFeature([Questions, Options])
  ],
  controllers: [UserController],
  providers: [UserService]
})
export class UserModule {}
```
