### ISSUE TITLE
@Table annotation is missing on class ... 

### ISSUE THREAD

**Issue by TalissonJunior** [RobinBuschmann/sequelize-typescript#370]
Hi,
I´m having the same issue as:
https://github.com/RobinBuschmann/sequelize-typescript/issues/178

It´s really weird because after i transpile the same code 3 times without changing anything from it i got the same error:
```
 @Table annotation is missing on class "ExampleEmployee"
```

Here's my model code sample
https://github.com/TalissonJunior/NodeExpressWebApi/blob/master/src/Models/Database/ExampleEmployee.ts#L4

the sequelize instantiation:
https://github.com/TalissonJunior/NodeExpressWebApi/blob/master/src/server.ts#L38

Any idea? is this really a random error? because sometimes works and sometimes don´t.
Here is a  full error message including the stack trace:
```

D:\Users\p066871\Desktop\testes\NodeExpressWebApi\node_modules\sequelize-typescript\lib\models\v4\Sequelize.js:53
                throw new Error(`@Table annotation is missing on class "${model['name']}"`);
                ^

Error: @Table annotation is missing on class "ExampleEmployee"
    at models.forEach.model (D:\Users\p066871\Desktop\testes\NodeExpressWebApi\node_modules\sequelize-typescript\lib\models\v4\Sequelize.js:53:23)
    at Array.forEach (<anonymous>)
    at Sequelize.defineModels (D:\Users\p066871\Desktop\testes\NodeExpressWebApi\node_modules\sequelize-typescript\lib\models\v4\Sequelize.js:48:16)
    at Sequelize.BaseSequelize.addModels (D:\Users\p066871\Desktop\testes\NodeExpressWebApi\node_modules\sequelize-typescript\lib\models\BaseSequelize.js:60:14)
    at Sequelize.BaseSequelize.init (D:\Users\p066871\Desktop\testes\NodeExpressWebApi\node_modules\sequelize-typescript\lib\models\BaseSequelize.js:69:18)
    at new Sequelize (D:\Users\p066871\Desktop\testes\NodeExpressWebApi\node_modules\sequelize-typescript\lib\models\v4\Sequelize.js:29:18)
    at Server.config (D:\Users\p066871\Desktop\testes\NodeExpressWebApi\build\server.js:30:9)
    at new Server (D:\Users\p066871\Desktop\testes\NodeExpressWebApi\build\server.js:23:14)
    at Object.<anonymous> (D:\Users\p066871\Desktop\testes\NodeExpressWebApi\build\server.js:75:19)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (D:\Users\p066871\Desktop\testes\NodeExpressWebApi\build\index.js:5:18)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3) ```

```

And if you want to test you can clone the repo:
https://github.com/TalissonJunior/NodeExpressWebApi
and then:

```npm install && gulp serve ```

**Comment by RobinBuschmann** [comment]
Hey @TalissonJunior, this could be an issue: https://github.com/serhiisol/node-decorators/blob/master/di/package.json#L7

Due to the explicit dependency to `reflect-metadata` in `@decorators/di` (or some other of your dependencies that has dep on `reflect-metadata`), I assume that you're ending up with multiple `reflect-metadata` packages in your project. This in turn can lead to such unexpected behaviour: One reflect-metadata package stores metadata in its own scope and the other reflect-metadata tries to retrieve this data from its scope, where of course this metadata cannot be found.

So you should report this issue to `@decorators/di` and other of your dependent packages that list `reflect-metadata` under `dependency`.

**Comment by TalissonJunior** [comment]
Problem solved, thanks man i remove the ```@decorators/di``` because i wasn´t really using it.
