### ISSUE TITLE
Error Schema no Found with Model

### ISSUE THREAD

**Issue by jhondavila** [RobinBuschmann/sequelize-typescript#371]
**how define to schema with sequelize in typescript ?** 

`@Table({
    timestamps: true,
    paranoid: true,
    tableName: "app",
    schema: "core"
})
export default class App extends Model<App> {
    @Column
    name: string;

    @Column
    alias: string;

    @Column
    icon_cls: string;

    @Column({
        type: DataType.TEXT
    })
    cfg: string;

    @Column
    id_ext: string
}

///console
////

Executing (default): DROP TABLE IF EXISTS "core"."app" CASCADE;
Executing (default): CREATE TABLE IF NOT EXISTS "core"."app" ("id"   SERIAL , "name" VARCHAR(255), "alias" VARCHAR(255), "icon_cls" VARCHAR(255), "cfg" TEXT, "id_ext" VARCHAR(255), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL, "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL, "deletedAt" TIMESTAMP WITH TIME ZONE, PRIMARY KEY ("id"));
**Unhandled rejection SequelizeDatabaseError: schema "core" does not exist**
    at Query.formatError (D:\Dev\Wx\node_modules\sequelize\lib\dialects\postgres\query.js:363:16)
    at query.catch.err (D:\Dev\Wx\node_modules\sequelize\lib\dialects\postgres\query.js:86:18)
    at tryCatcher (D:\Dev\Wx\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (D:\Dev\Wx\node_modules\bluebird\js\release\promise.js:512:31)
    at Promise._settlePromise (D:\Dev\Wx\node_modules\bluebird\js\release\promise.js:569:18)
    at Promise._settlePromise0 (D:\Dev\Wx\node_modules\bluebird\js\release\promise.js:614:10)
    at Promise._settlePromises (D:\Dev\Wx\node_modules\bluebird\js\release\promise.js:689:18)
    at Async._drainQueue (D:\Dev\Wx\node_modules\bluebird\js\release\async.js:133:16)
    at Async._drainQueues (D:\Dev\Wx\node_modules\bluebird\js\release\async.js:143:10)
    at Immediate.Async.drainQueues (D:\Dev\Wx\node_modules\bluebird\js\release\async.js:17:14)
    at runCallback (timers.js:781:20)
    at tryOnImmediate (timers.js:743:5)
    at processImmediate [as _immediateCallback] (timers.js:714:5)

`

**Comment by RobinBuschmann** [comment]
Hey @jhondavila, I haven’t used this feature before but I assume you need to create the schema before: https://stackoverflow.com/a/42505603

**Comment by RobinBuschmann** [comment]
@jhondavila Does my suggestion solve your issue?

**Comment by RobinBuschmann** [comment]
Close this issue due to inactivity
