### ISSUE TITLE
Error: Cannot find module 

### ISSUE THREAD

**Issue by vschoener** [RobinBuschmann/sequelize-typescript#394]
Hey,

I just run into an issue trying to load the models. It says:
`'/app/src/models/user'`

I use webpack to build / watch and hot reload the server. (Works nice).

Lately, I tried to follow your guide and use this library, I created this config:

```
// database is type ISequelizeUriConfig;
database: {
    url: process.env.DATABASE_URL || 'postgres://user:pass@example.com:5432/dbname',
    modelPaths: [ `${appRoot.path}/src/models` ]
  }

// And later in the code, this.config == database above
this.sequelize = new Sequelize(this.config);
```

My models folder contain only one file, user.ts :

```
import {
  Model,
  Table,
  Column,
  Unique } from "sequelize-typescript";

@Table({
  timestamps: true
})
export class User extends Model<User> {
  @Column
  firstName: string;

  @Column
  lastName: string;

  @Column
  @Unique
  email: string;

  @Column
  password: string;
}
```
And when I run my code, I get the error that says it can't find the file user.

Do you guys have an idea? DId I miss something ?

Or I miss understand  and don't use  my typescript compiled code (it's just one file and not the classic architecture when it runs)

**Comment by vschoener** [comment]
Ok so, to fix my issue, I use this way:
```
/**
   * Get models
   */
  get models(): Array<typeof Model> {
    const models: Array<typeof Model> = [
      User,
// Add all the models 
    ];

    return models;
  }
// ...
// Then
this.sequelize.addModels(this.models);
```

Don't like having to add a model one by one, but for now I'll deal with :)

**Comment by RobinBuschmann** [comment]
@vschoener Can you provide the exact error message including stack trace? Or If you have an example repo which reproduces the issue?

**Comment by vschoener** [comment]
@RobinBuschmann Of course

Since I created a new model so this is `activity` instead of `user` but the issue remains the same.
And I now use `export class User extends Model<User>` when using glob/path cause I don't have the same file/class name identically (cf documentation).

Here is the stack I got:

```
error:  Error: Cannot find module '/app/src/api/v1/activity/activty.model'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:594:15)
    at Function.Module._load (internal/modules/cjs/loader.js:520:25)
    at Module.require (internal/modules/cjs/loader.js:650:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at /app/node_modules/sequelize-typescript/lib/services/models.js:175:30
    at Array.map (<anonymous>)
    at /app/node_modules/sequelize-typescript/lib/services/models.js:174:18
    at Array.reduce (<anonymous>)
    at Object.getModels (/app/node_modules/sequelize-typescript/lib/services/models.js:166:20)
    at Sequelize.BaseSequelize.addModels (/app/node_modules/sequelize-typescript/lib/models/BaseSequelize.js:59:31)
    at Sequelize.BaseSequelize.init (/app/node_modules/sequelize-typescript/lib/models/BaseSequelize.js:69:18)
    at new Sequelize (/app/node_modules/sequelize-typescript/lib/models/v4/Sequelize.js:29:18)
    at Database.<anonymous> (/app/build/main.dac4d85e1050e819b83a.hot-update.js:183:30)
    at Generator.next (<anonymous>)
    at /app/build/main.dac4d85e1050e819b83a.hot-update.js:154:71
    at new Promise (<anonymous>)
    at exports.modules../src/database/index.ts.__awaiter (/app/build/main.dac4d85e1050e819b83a.hot-update.js:150:12)
    at Database.connect (/app/build/main.dac4d85e1050e819b83a.hot-update.js:181:16)
    at App.<anonymous> (/app/build/main.ad3eadd798ad50e30726.hot-update.js:104:33)
    at Generator.next (<anonymous>)
    at /app/build/main.ad3eadd798ad50e30726.hot-update.js:18:71
    at new Promise (<anonymous>)
    at exports.modules../src/app.ts.__awaiter (/app/build/main.ad3eadd798ad50e30726.hot-update.js:14:12)
    at App.start (/app/build/main.ad3eadd798ad50e30726.hot-update.js:103:16)
    at ./src/main.ts.bootstrap_1.default.stop.then (/app/build/server.js:1351:59)
```

**Comment by RobinBuschmann** [comment]
@vschoener This is definitely a node error. Your path is wrong. Could be something to do with the starting `/` which means the root path here.

**Comment by RobinBuschmann** [comment]
Close this issue due to inactivity.
