### ISSUE TITLE
Add pkg support 

### ISSUE THREAD

**Issue by yantrab** [RobinBuschmann/sequelize-typescript#482]
When i run executable  file, that building with pkg, i get this error:

Cannot find module './v4/Model'
1) If you want to compile the package/file into executable, please pay attention to compilation warnings and specify a literal in 'require' call. 2) If you don't want to compile the package/file into executable and want to 'require' it from filesystem (likely plugin), specify an absolute path
in 'require' call using process.cwd() or process.execPath.
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:592:15)
    at Function.Module._resolveFilename (pkg/prelude/bootstrap.js:1278:46)
    at Function.Module._load (internal/modules/cjs/loader.js:518:25)
    at Module.require (internal/modules/cjs/loader.js:648:17)
    at Module.require (pkg/prelude/bootstrap.js:1157:31)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (C:\snapshot\the marker graph\node_modules\sequelize-typescript\lib\models\Model.js:6:13)
    at Module._compile (pkg/prelude/bootstrap.js:1252:22)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:711:10)
    at Module.load (internal/modules/cjs/loader.js:610:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:549:12)
    at Function.Module._load (internal/modules/cjs/loader.js:541:3)
    at Module.require (internal/modules/cjs/loader.js:648:17)
    at Module.require (pkg/prelude/bootstrap.js:1157:31)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (C:\snapshot\the marker graph\node_modules\sequelize-typescript\lib\services\models.js:14:15)
    at Module._compile (pkg/prelude/bootstrap.js:1252:22)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:711:10)
    at Module.load (internal/modules/cjs/loader.js:610:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:549:12)
    at Function.Module._load (internal/modules/cjs/loader.js:541:3)
    at Module.require (internal/modules/cjs/loader.js:648:17)

**Comment by RobinBuschmann** [comment]
@yantrab Can you provide an example repo, so that I can have a look?

**Comment by RobinBuschmann** [comment]
Close this issue due to inactivity
