### ISSUE TITLE
How to add 'FULLTEXT' index?

### ISSUE THREAD

**Issue by 695954085** [RobinBuschmann/sequelize-typescript#489]
Hi:
    My entity file is like this
<pre>
import {
  Table,
  Column,
  Model,
  ForeignKey,
  DataType,
  BelongsTo,
  NotNull,
} from 'sequelize-typescript';
import { Product } from '../product/product.entity';

@Table({
  engine: 'MyISAM',
  indexes: [
    {
      index: 'FULLTEXT',
      fields: ['note_text'],
      name: 'note_text_idx',
    },
  ],
})
export class ProductNote extends Model<ProductNote> {
  @NotNull
  @Column({ primaryKey: true })
  note_id: number;

  @NotNull
  @ForeignKey(() => Product)
  @Column(DataType.CHAR(10))
  prod_id: string;

  @NotNull
  @Column({ type: DataType.DATE })
  note_date: Date;

  @Column({ type: DataType.TEXT })
  note_text: string;

  @BelongsTo(() => Product)
  product: Product;
}
</pre>

----
But my running result is like this. 'Fulltext' seems to be ignored.
<pre>
Executing (default): CREATE TABLE IF NOT EXISTS `ProductNote` (`note_id` INTEGER , `prod_id` CHAR(10), `note_date` DATETIME, `note_text` TEXT, PRIMARY KEY (`note_id`), FOREIGN KEY (`prod_id`) REFERENCES `Product` (`prod_id`) ON DELETE SET NULL ON UPDATE CASCADE) ENGINE=MyISAM;
Executing (default): SHOW INDEX FROM `ProductNote` FROM `order`
Executing (default): ALTER TABLE `ProductNote` ADD INDEX `note_text_idx` (`note_text`)
[Nest] 133268   - 2018-12-4 10:25:22   [ExceptionHandler] Specified key was too long; max key length is 1000 bytes +235ms
SequelizeDatabaseError: Specified key was too long; max key length is 1000 bytes
    at Query.formatError (C:\Users\canno30\Desktop\order-system\node_modules\sequelize\lib\dialects\mysql\query.js:247:16)
    at Query.handler [as onResult] (C:\Users\canno30\Desktop\order-system\node_modules\sequelize\lib\dialects\mysql\query.js:68:23)
    at Query.execute (C:\Users\canno30\Desktop\order-system\node_modules\mysql2\lib\commands\command.js:30:14)
    at Connection.handlePacket (C:\Users\canno30\Desktop\order-system\node_modules\mysql2\lib\connection.js:455:32)
    at PacketParser.onPacket (C:\Users\canno30\Desktop\order-system\node_modules\mysql2\lib\connection.js:73:18)
    at PacketParser.executeStart (C:\Users\canno30\Desktop\order-system\node_modules\mysql2\lib\packet_parser.js:75:16)
    at Socket.<anonymous> (C:\Users\canno30\Desktop\order-system\node_modules\mysql2\lib\connection.js:80:31)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at TCP.onread (net.js:601:20)
 1: v8::internal::compiler::Type::Negative31
 2: v8::internal::wasm::SignatureMap::Find
 3: v8::internal::Builtins::CallableFor
 4: v8::internal::Builtins::CallableFor
 5: v8::internal::Builtins::CallableFor
 6: 000002255AF043C1
error Command failed with exit code 3.
</pre>

**Comment by RobinBuschmann** [comment]
Hey @695954085, did you find a way to solve your issue?

**Comment by destyk** [comment]
If this is useful to someone else:
https://github.com/sequelize/sequelize-typescript#indexes
