### ISSUE TITLE
表关联时，一直报错说模型找不到

### ISSUE THREAD

**Issue by diy4869** [RobinBuschmann/sequelize-typescript#579]
在做关联查询的时候，一直报错说找不到模型，有三个表，用户，收藏，番剧表，实现用户对番剧的收藏效果。
收藏表保存了用户的uid和bangumi_id根据这2个去查询数据
多对多的查询
下面是用户表的数据
`
import Bangumi from './bangumi'
import collection from './collection'
import {Table, Column, Model, AutoIncrement, PrimaryKey, AllowNull, BelongsToMany, ForeignKey} from 'sequelize-typescript'

// import doSQL from './doSQL'

console.log(collection)
// console.log(doSQL)
@Table({
  timestamps: true,
  paranoid: true,
  tableName: 'User',
  createdAt: 'createTime',
  updatedAt: false,
  deletedAt: false
})
export default class User extends Model<User> {
  @ForeignKey(() => collection)
  @AutoIncrement
  @PrimaryKey
  @Column
  id: number;

  @AllowNull(false)
  @Column
  username: string;

  @AllowNull(false)
  @Column
  password: string;
  
  @Column
  sex: string;

  @Column
  avator: string;

  @BelongsToMany(() => Bangumi ,()=> collection)
  bangumies: Bangumi[];
}
`
收藏表的内容
`
import {Table, Column, Model,BelongsTo,  AutoIncrement, PrimaryKey, BelongsToMany, ForeignKey, Scopes} from 'sequelize-typescript'
import User from './user';
import Bangumi from './bangumi'

@Table({
  timestamps: true,
  paranoid: true,
  tableName: 'collection',
  createdAt: 'createTime',
  updatedAt: false,
  deletedAt: false
})
export default class Collection extends Model<Collection> {
  @AutoIncrement
  @PrimaryKey
  @Column
  id: number;
  
  @ForeignKey(() => User)
  @Column
  uid: number

  @ForeignKey(() => Bangumi)
  @Column
  Bangumi_id: number
}
`
番剧表的内容
`
import {Table, Column, Model, AutoIncrement, PrimaryKey, AllowNull, Length, BelongsToMany, ForeignKey} from 'sequelize-typescript'
import Collection from './collection';
import User from './user'

@Table({
  timestamps: true,
  paranoid: true,
  tableName: 'bangumi',
  createdAt: 'createTime',
  updatedAt: false,
  deletedAt: false
})
export default class Bangumi extends Model<Bangumi> {
  @AutoIncrement
  @PrimaryKey
  @Column
  id: number;

  @Column
  origin_name: string;

  @Column
  bangumiName: string;
  
  @Column
  cover: string;

  @Column
  startTime: Date;

  @Length({
    max: 1
  })
  @Column
  isFinish: number;

  @Column
  description: string;

  @Column
  company: string;

  @Column
  area: string;

  @Column
  type: string;

  @Length({
    max: 4
  })
  @Column
  year: number;

  @Column
  quarter: string;

  @Column
  episode: string;

  @BelongsToMany(() => User, () => Collection)
  collectionies: Collection[];
}
`

**Comment by RobinBuschmann** [comment]
@diy4869 Thanks for reporting. Can you at least provide an error message or much better an example repo?

**Comment by diy4869** [comment]
这个是项目地址，没办法传图片所以。。。
[project address](https://github.com/last4869/animation_server)

user.ts:7
Error: **Cannot find module 'src/models/model/collection**'
`
source-map-support.js:444
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:582:15)
    at Function.Module._load (internal/modules/cjs/loader.js:508:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (d:\private\test\src\controller\user.ts:2:1)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Module.m._compile (D:\private\test\node_modules\_ts-node@8.0.3@ts-node\src\index.ts:414:23)
    at Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Object.require.extensions.(anonymous function) [as .ts] (D:\private\test\node_modules\_ts-node@8.0.3@ts-node\src\index.ts:417:12)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (d:\private\test\src\router.ts:1:1)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Module.m._compile (D:\private\test\node_modules\_ts-node@8.0.3@ts-node\src\index.ts:414:23)
    at Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Object.require.extensions.(anonymous function) [as .ts] (D:\private\test\node_modules\_ts-node@8.0.3@ts-node\src\index.ts:417:12)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
`

**Comment by RobinBuschmann** [comment]
Unfortunately your github project is mostly empty (https://github.com/last4869/animation_server)

**Comment by zzyyzz1992** [comment]
@diy4869 我这边编译没有出现Cannot find moduled的错误。

**Comment by RobinBuschmann** [comment]
Closing this due to inactivity.
