### ISSUE TITLE
Cant Use DefaultScope with sequelize.literal

### ISSUE THREAD

**Issue by vekexasia** [RobinBuschmann/sequelize-typescript#614]
**Versions**

- sequelize: 5.8.5
- sequelize-typescript: 1.0.0-alpha.9
- typescript: 3.4.5

**I'm submitting a ...** 

[x] bug report
[ ] feature request

**Actual behavior:**
calling `.findAll` + default scope with a custom attribute defined with a literal.

**Expected behavior:**

**Steps to reproduce:**
This code producess
```ts
@Table({tableName: 'brocca'})
    @DefaultScope({
      attributes: [
        [sequelize.literal('meow'), 'aaa'],
      ],
    })
    class Brocca extends Model<Brocca> {

    }
    const bit = new Sequelize({dialect: 'postgres'});
    bit.addModels([Brocca]);
    await Brocca.findAll();
```

Stacktrace: 
```
TypeError: attr[0].includes is not a function
    at attributes.map.attr (node_modules/sequelize/lib/dialects/abstract/query-generator.js:1383:29)
    at Array.map (<anonymous>)
    at PostgresQueryGenerator.escapeAttributes (node_modules/sequelize/lib/dialects/abstract/query-generator.js:1368:37)
    at PostgresQueryGenerator.selectQuery (node_modules/sequelize/lib/dialects/abstract/query-generator.js:1134:28)
    at QueryInterface.select (node_modules/sequelize/lib/query-interface.js:1120:27)
    at Promise.try.then.then.then (node_modules/sequelize/lib/model.js:1744:34)
    at tryCatcher (node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (node_modules/bluebird/js/release/promise.js:694:18)
    at _drainQueueStep (node_modules/bluebird/js/release/async.js:138:12)
    at _drainQueue (node_modules/bluebird/js/release/async.js:131:9)
    at Async._drainQueues (node_modules/bluebird/js/release/async.js:147:5)
    at Immediate.Async.drainQueues [as _onImmediate] (node_modules/bluebird/js/release/async.js:17:14)
```

**Related code:**
...

**Comment by vekexasia** [comment]
Hey @RobinBuschmann 

Apparently the same codebase works if using plain "sequelize" code. Here a snippet showing sequel-typescript vs sequelize code.

```ts
import * as sequelize from 'sequelize';
import { Sequelize as SSequelize } from 'sequelize';
import { DefaultScope, Model, Sequelize, Table } from 'sequelize-typescript';

describe('test', () => {
  it('test', async () => {
    // console.log('a');
    @Table({ tableName: 'brocca' })
    @DefaultScope({
      attributes: [[sequelize.literal('meow'), 'aaa']],
    })
    class Brocca extends Model<Brocca> {}
    const bit = new Sequelize({ dialect: 'postgres', logging: true });
    bit.addModels([Brocca]);
    await Brocca.findAll();

  });
  it('test2', async () => {
    class Brocca extends Model {}
    const s = new SSequelize('test', 'test', 'password', {dialect: 'postgres', logging: true});
    Brocca.init({}, {
      defaultScope: {
        attributes: [[sequelize.literal('meow'), 'aaa']],
      },
      sequelize: s,
      tableName: 'brocca',
    });
    console.log('hey');
    await Brocca.findAll();
  });
});
```

**Comment by RobinBuschmann** [comment]
Hey @vekexasia, thanks for reporting. But this is fixed with the latest pre-major release `sequelize-typescript@1.0.0-beta.3`. Passing objects to `@Scopes` and `@DefaultScope` is deprecated there - Use it like so instead:
```ts
    @DefaultScope(() => ({ // <-- lambda
      attributes: [[sequelize.literal('meow'), 'aaa']],
    }))
```
Hope this helps!

**Comment by RobinBuschmann** [comment]
@vekexasia Does my suggestion solve your issue? Can we close this now?

**Comment by vekexasia** [comment]
yes sorry :)
