### ISSUE TITLE
include[].on get an error:  Error: Invalid value { '$col': '...' }

### ISSUE THREAD

**Issue by dancon** [RobinBuschmann/sequelize-typescript#639]
**Versions**

- sequelize: 5.8.8
- sequelize-typescript: 1.0.0-alpha.9
- typescript: 3.4.3

**I'm submitting a ...** 

[x] bug report
[ ] feature request

**Actual behavior:**

code as below

```
PSMUserRelation.findAll({
        include: [
          {
            model: User,
            as: 'maintainerInfo',
            on: {
              '$PSMUserRelation.maintainer$': { $col: 'maintainerInfo.user_id' }
            },
          }
        ]
      })
```

get the error:

```
Error: Invalid value { '$col': 'maintainerInfo.user_id' }
    at Object.escape (/server/node_modules/sequelize/lib/sql-string.js:65:11)
    at MySQLQueryGenerator.escape (/server/node_modules/sequelize/lib/dialects/abstract/query-generator.js:966:22)
    at MySQLQueryGenerator._whereParseSingleValueObject (/server/node_modules/sequelize/lib/dialects/abstract/query-generator.js:2433:41)
    at MySQLQueryGenerator.whereItemQuery (/server/node_modules/sequelize/lib/dialects/abstract/query-generator.js:2151:19)
    at Utils.getComplexKeys.forEach.prop (/server/node_modules/sequelize/lib/dialects/abstract/query-generator.js:2050:25)
    at Array.forEach (<anonymous>)
    at MySQLQueryGenerator.whereItemsQuery (/server/node_modules/sequelize/lib/dialects/abstract/query-gen...
```

Is there some thing I missing?

**Expected behavior:**

work as it is

**Comment by RobinBuschmann** [comment]
Hey @dancon, the `$col` syntax isn't supported anymore by sequelize. Use the following instead:
```ts
import {Op} from 'sequelize';

...
            on: {
              '$PSMUserRelation.maintainer$': { [Op.col]: 'maintainerInfo.user_id' }
            },
```
See [docs](http://docs.sequelizejs.com/manual/querying.html#operators) for further information.

Hope this helps. Feel free to close this issue if my answer solves your issue!

**Comment by dancon** [comment]
Got it, really appreciate it!

**Comment by dancon** [comment]
I get
