### ISSUE TITLE
UnhandledPromiseRejectionWarning: Error: Model not initialized: Member "call" cannot be called. "Model" needs to be added to a Sequelize instance.

### ISSUE THREAD

**Issue by Satont** [RobinBuschmann/sequelize-typescript#689]
**Versions**

- sequelize: 5.19.5
- sequelize-typescript: 1.0.0
- typescript: 3.6.4
- "pg": "^7.12.1",
- "pg-hstore": "^2.3.3",

**I'm submitting a ...** 

[x] bug report
[ ] feature request

**Actual behavior:**

I'm using postgresql, and when i'm trying to call findOne() got this error.
```
Executing (default): SELECT "id", "follows" FROM "users" AS "User" WHERE "User"."id" = 123;
(node:13436) UnhandledPromiseRejectionWarning: Error: Model not initialized: Member "call" cannot be called. "Model" needs to be added to a Sequelize instance.
    at Function.Model.<computed> [as call] (C:\Projects\vk-twitch-notifier\node_modules\sequelize-typescript\dist\model\model\model.js:115:23)
    at new User (C:\Projects\vk-twitch-notifier\dest\models\User.js:53:94)
    at Function.build (C:\Projects\vk-twitch-notifier\node_modules\sequelize\lib\model.js:2166:12)
    at Function.Model.<computed> (C:\Projects\vk-twitch-notifier\node_modules\sequelize-typescript\dist\model\model\model.js:117:28)
    at Function.Model.<computed> [as build] (C:\Projects\vk-twitch-notifier\node_modules\sequelize-typescript\dist\model\model\model.js:129:28)
    at C:\Projects\vk-twitch-notifier\node_modules\sequelize\lib\model.js:2186:41
    at Array.map (<anonymous>)
    at Function.bulkBuild (C:\Projects\vk-twitch-notifier\node_modules\sequelize\lib\model.js:2186:22)
    at Function.Model.<computed> (C:\Projects\vk-twitch-notifier\node_modules\sequelize-typescript\dist\model\model\model.js:117:28)
    at Function.Model.<computed> [as bulkBuild] (C:\Projects\vk-twitch-notifier\node_modules\sequelize-typescript\dist\model\model\model.js:129:28)
    at Query.handleSelectQuery (C:\Projects\vk-twitch-notifier\node_modules\sequelize\lib\dialects\abstract\query.js:297:27)
    at C:\Projects\vk-twitch-notifier\node_modules\sequelize\lib\dialects\postgres\query.js:196:23
    at tryCatcher (C:\Projects\vk-twitch-notifier\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (C:\Projects\vk-twitch-notifier\node_modules\bluebird\js\release\promise.js:547:31)
    at Promise._settlePromise (C:\Projects\vk-twitch-notifier\node_modules\bluebird\js\release\promise.js:604:18)
    at Promise._settlePromise0 (C:\Projects\vk-twitch-notifier\node_modules\bluebird\js\release\promise.js:649:10)
    at Promise._settlePromises (C:\Projects\vk-twitch-notifier\node_modules\bluebird\js\release\promise.js:729:18)
    at _drainQueueStep (C:\Projects\vk-twitch-notifier\node_modules\bluebird\js\release\async.js:93:12)
    at _drainQueue (C:\Projects\vk-twitch-notifier\node_modules\bluebird\js\release\async.js:86:9)
    at Async._drainQueues (C:\Projects\vk-twitch-notifier\node_modules\bluebird\js\release\async.js:102:5)
    at Immediate.Async.drainQueues [as _onImmediate] (C:\Projects\vk-twitch-notifier\node_modules\bluebird\js\release\async.js:15:14)
    at processImmediate (internal/timers.js:439:21)
(node:13436) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:13436) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```
So weird i tryed sqlite provider, and it returns me `null`, without this error.
Also i added 
```ts
sequelize.authenticate()
  .then(() => {
    sequelize.sync().then(() => connected = true).then(() => info('Succesfuly connected to db.')).then(() => console.log(sequelize.models))
  })
```
For check does my models loaded, and it logged me correct object `{ User: User, Channel: Channel }`
**Expected behavior:**

Should return null or data.
**Steps to reproduce:**

**Related code:**

```ts
import { User } from '../models/User'
async function test() {
const user = await User.findOne({where: { id: 123 }})
console.log(user)
}
```
Or check repository: https://github.com/Satont/twitch-vk-notifier
Sequelize setup: https://github.com/Satont/twitch-vk-notifier/blob/master/src/libs/db.ts
Where i'm trying to call this: https://github.com/Satont/twitch-vk-notifier/blob/master/src/libs/vk.ts#L11
Models folder: https://github.com/Satont/twitch-vk-notifier/tree/master/src/models

**Comment by Satont** [comment]
Again, when i tested this on sqlite i got it working (i think, because my code at https://github.com/Satont/twitch-vk-notifier/blob/master/src/libs/vk.ts#L11 showed me `null` in console), postgre not.

**Comment by RobinBuschmann** [comment]
Hey @Satont, sry for the late reply. Can you provide a simpler example which reproduces the issue? So that I don't have to set up twitch? Just the a file with the sequelize setup, a file with the model and another with a method which makes the database request? Thank you

**Comment by Satont** [comment]
Hi, just setuped project for you.
https://github.com/Satont/sequelize-typescript689
Set up your db credentials at src/libs/db.ts, after that just use
`npm i; npm run build; node dest/app.js`

**Comment by Satont** [comment]
Nah, nevermind. I removed babel intermediary, and moved to `tsc`, my problem is gone.
