### ISSUE TITLE
i have update command who doesnt work

### ISSUE THREAD

**Issue by linger123** [RobinBuschmann/sequelize-typescript#694]
await User.update({
                    logout_at: utc.format('YYYY-MM-DD HH:mm:ss')
                }, {
                    where: {
                        id: Sequelize.fn('unhex', id)
                    }
                });
that is error:

 UnhandledPromiseRejectionWarning: Error: Cannot pass SequelizeMethod as a bind parameter - use escape instead
[Node]     at MySQLQueryGenerator.format (D:\Web\server\node_modules\sequelize\lib\dialects\abstract\query-generator.js:1005:15)
[Node]     at MySQLQueryGenerator.whereItemQuery (D:\Web\server\node_modules\sequelize\lib\dialects\abstract\query-generator.js:2282:46)
[Node]     at Utils.getComplexKeys.forEach.prop (D:\Web\server\node_modules\sequelize\lib\dialects\abstract\query-generator.js:2173:25)
[Node]     at Array.forEach (<anonymous>)
[Node]     at MySQLQueryGenerator.whereItemsQuery (D:\Web\server\node_modules\sequelize\lib\dialects\abstract\query-generator.js:2171:35)
[Node]     at MySQLQueryGenerator.whereQuery (D:\Web\server\node_modules\sequelize\lib\dialects\abstract\query-generator.js:2144:24)
[Node]     at MySQLQueryGenerator.updateQuery (D:\Web\server\node_modules\sequelize\lib\dialects\abstract\query-generator.js:435:116)
[Node]     at QueryInterface.bulkUpdate (D:\Web\server\node_modules\sequelize\lib\query-interface.js:1038:37)
[Node]     at Promise.try.then.then.then.results (D:\Web\server\node_modules\sequelize\lib\model.js:3222:34)
[Node]     at tryCatcher (D:\Web\server\node_modules\bluebird\js\release\util.js:16:23)
[Node]     at Promise._settlePromiseFromHandler (D:\Web\server\node_modules\bluebird\js\release\promise.js:517:31)
[Node]     at Promise._settlePromise (D:\Web\server\node_modules\bluebird\js\release\promise.js:574:18)
[Node]     at Promise._settlePromise0 (D:\Web\server\node_modules\bluebird\js\release\promise.js:619:10)
[Node]     at Promise._settlePromises (D:\Web\server\node_modules\bluebird\js\release\promise.js:699:18)
[Node]     at _drainQueueStep (D:\Web\server\node_modules\bluebird\js\release\async.js:138:12)
[Node]     at _drainQueue (D:\Web\server\node_modules\bluebird\js\release\async.js:131:9)
[Node]     at Async._drainQueues (D:\Web\server\node_modules\bluebird\js\release\async.js:147:5)
[Node]     at Immediate.Async.drainQueues [as _onImmediate] (D:\Web\server\node_modules\bluebird\js\release\async.js:17:14)
[Node]     at runCallback (timers.js:705:18)
[Node]     at tryOnImmediate (timers.js:676:5)
[Node]     at processImmediate (timers.js:658:5)

**Comment by RobinBuschmann** [comment]
Hey @linger123 Can you provide more information about where `utc.format` comes from?

**Comment by RobinBuschmann** [comment]
Closing this due to inactivity
