### ISSUE TITLE
sequelize-typescript tests on windows fail

### ISSUE THREAD

**Issue by cjancsar** [RobinBuschmann/sequelize-typescript#713]
**I'm submitting a ...** 
[ x ] bug report
[ ] feature request

**Actual behavior:**

Running the `sequelize-typescript` project tests on windows does not work.

```
return new TSError(diagnosticText, diagnosticCodes)
           ^
TSError: ⨯ Unable to compile TypeScript:
src/model/column/attribute-service.ts(11,30): error TS2339: Property 'getMetadata' does not exist on type 'typeof Reflect'.
src/model/column/attribute-service.ts(29,11): error TS2339: Property 'defineMetadata' does not exist on type 'typeof Reflect'.

    at createTSError (C:\Users\...\GitHub\sequelize-typescript\node_modules\ts-node\src\index.ts:261:12)
    at getOutput (C:\Users\...\GitHub\sequelize-typescript\node_modules\ts-node\src\index.ts:367:40)
    at Object.compile (C:\Users\...\GitHub\sequelize-typescript\node_modules\ts-node\src\index.ts:558:11)
    at Module.m._compile (C:\Users\...\GitHub\sequelize-typescript\node_modules\ts-node\src\index.ts:439:43)
    at module.exports (C:\Users\...\GitHub\sequelize-typescript\node_modules\nyc\node_modules\default-require-extensions\js.js:7:9)
    at C:\Users\...\GitHub\sequelize-typescript\node_modules\nyc\node_modules\append-transform\index.js:62:4
    at require.extensions.(anonymous function) (C:\Users\...\GitHub\sequelize-typescript\node_modules\ts-node\src\index.ts:442:12)
    at Object.<anonymous> (C:\Users\...\GitHub\sequelize-typescript\node_modules\nyc\node_modules\append-transform\index.js:62:4)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (C:\Users\...\GitHub\sequelize-typescript\src\sequelize\sequelize\sequelize.ts:1:8855)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Module.replacementCompile (C:\Users\...\GitHub\sequelize-typescript\node_modules\nyc\node_modules\append-transform\index.js:58:13)
    at Module.m._compile (C:\Users\...\GitHub\sequelize-typescript\node_modules\ts-node\src\index.ts:439:23)
    at module.exports (C:\Users\...\GitHub\sequelize-typescript\node_modules\nyc\node_modules\default-require-extensions\js.js:7:9)
    at C:\Users\...\GitHub\sequelize-typescript\node_modules\nyc\node_modules\append-transform\index.js:62:4
    at require.extensions.(anonymous function) (C:\Users\...\GitHub\sequelize-typescript\node_modules\ts-node\src\index.ts:442:12)
    at Object.<anonymous> (C:\Users\...\GitHub\sequelize-typescript\node_modules\nyc\node_modules\append-transform\index.js:62:4)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (C:\Users\...\GitHub\sequelize-typescript\test\utils\sequelize.ts:3:21)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Module.replacementCompile (C:\Users\...\GitHub\sequelize-typescript\node_modules\nyc\node_modules\append-transform\index.js:58:13)
    at Module.m._compile (C:\Users\...\GitHub\sequelize-typescript\node_modules\ts-node\src\index.ts:439:23)
    at module.exports (C:\Users\...\GitHub\sequelize-typescript\node_modules\nyc\node_modules\default-require-extensions\js.js:7:9)
    at C:\Users\...\GitHub\sequelize-typescript\node_modules\nyc\node_modules\append-transform\index.js:62:4
    at require.extensions.(anonymous function) (C:\Users\...\GitHub\sequelize-typescript\node_modules\ts-node\src\index.ts:442:12)
    at Object.<anonymous> (C:\Users\...\GitHub\sequelize-typescript\node_modules\nyc\node_modules\append-transform\index.js:62:4)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (C:\Users\...\GitHub\sequelize-typescript\test\specs\annotations\belongs-to-many.spec.ts:16:21)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Module.replacementCompile (C:\Users\...\GitHub\sequelize-typescript\node_modules\nyc\node_modules\append-transform\index.js:58:13)
    at Module.m._compile (C:\Users\...\GitHub\sequelize-typescript\node_modules\ts-node\src\index.ts:439:23)
    at module.exports (C:\Users\...\GitHub\sequelize-typescript\node_modules\nyc\node_modules\default-require-extensions\js.js:7:9)
    at C:\Users\...\GitHub\sequelize-typescript\node_modules\nyc\node_modules\append-transform\index.js:62:4
    at require.extensions.(anonymous function) (C:\Users\...\GitHub\sequelize-typescript\node_modules\ts-node\src\index.ts:442:12)
    at Object.<anonymous> (C:\Users\...\GitHub\sequelize-typescript\node_modules\nyc\node_modules\append-transform\index.js:62:4)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at C:\Users\...\GitHub\sequelize-typescript\node_modules\mocha\lib\mocha.js:250:27
    at Array.forEach (<anonymous>)
    at Mocha.loadFiles (C:\Users\...\GitHub\sequelize-typescript\node_modules\mocha\lib\mocha.js:247:14)
    at Mocha.run (C:\Users\...\GitHub\sequelize-typescript\node_modules\mocha\lib\mocha.js:576:10)
    at Object.<anonymous> (C:\Users\...\GitHub\sequelize-typescript\node_modules\mocha\bin\_mocha:637:18)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Module.replacementCompile (C:\Users\...\GitHub\sequelize-typescript\node_modules\nyc\node_modules\append-transform\index.js:58:13)
    at Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Object.<anonymous> (C:\Users\...\GitHub\sequelize-typescript\node_modules\nyc\node_modules\append-transform\index.js:62:4)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
    at runMain (C:\Users\...\.node-spawn-wrap-10832-6d6087a62807\node:68:10)
    at Function.<anonymous> (C:\Users\...\.node-spawn-wrap-10832-6d6087a62807\node:171:5)
    at Object.<anonymous> (C:\Users\...\GitHub\sequelize-typescript\node_modules\nyc\bin\wrap.js:23:4)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
    at C:\Users\...\.node-spawn-wrap-10832-6d6087a62807\node:178:8
    at Object.<anonymous> (C:\Users\...\.node-spawn-wrap-10832-6d6087a62807\node:181:3)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)
```

**Expected behavior:**
Tests should run

**Steps to reproduce:**
1. Clone project on windows 10
2. `npm install`
3. `npm run build`
4. `npm run cover`

**Comment by RobinBuschmann** [comment]
He @cjancsar, thanks for reporting. When you import `reflect-metadata` (`import 'reflect-metadata';`) at the top of the file `attribute-service.ts, is the error still thrown?

**Comment by RobinBuschmann** [comment]
@cjancsar Ping ;)

**Comment by RobinBuschmann** [comment]
Closing this due to inactivity
