### ISSUE TITLE
Extend model is not supported?

### ISSUE THREAD

**Issue by hiradimir** [RobinBuschmann/sequelize-typescript#74]
I want to extend model.

I need field of createAt/updatedAt/deletedAt to all model.
I am trying some case of extends models.
Some case looks like works well.  
https://circleci.com/gh/hiradimir/sequelize-typescript-extends-belongTo/4

![image](https://user-images.githubusercontent.com/1043276/28741669-8510eb7a-7456-11e7-9a15-8026d250eb42.png)

## But, some case does not working.
ex) Having HasMany fields extends class contains belongTo,

https://github.com/hiradimir/sequelize-typescript-extends-belongTo/tree/master/src/ts/main/models

https://circleci.com/gh/hiradimir/sequelize-typescript-extends-belongTo/5
Please see `yarn test` section.

```log
  1) util model test sync:
     Error: Foreign key for "Player" is missing on "Player".
      at Object.getForeignKey (node_modules/sequelize-typescript/lib/services/association.js:74:11)
      at node_modules/sequelize-typescript/lib/models/BaseSequelize.js:72:74
      at Array.forEach (native)
      at node_modules/sequelize-typescript/lib/models/BaseSequelize.js:71:26
      at Array.forEach (native)
      at Sequelize.BaseSequelize.associateModels (node_modules/sequelize-typescript/lib/models/BaseSequelize.js:67:16)
      at Sequelize.BaseSequelize.addModels (node_modules/sequelize-typescript/lib/models/BaseSequelize.js:54:14)
      at Sequelize.BaseSequelize.init (node_modules/sequelize-typescript/lib/models/BaseSequelize.js:60:18)
      at new Sequelize (node_modules/sequelize-typescript/lib/models/v4/Sequelize.js:26:14)
      at Context.it (src/ts/spec/models.spec.ts:10:31)
```

**Comment by RobinBuschmann** [comment]
@hiradimir, I investigated this. It is a bug, unfortunately. Thanks for reporting.

I cannot think of any workaround currently. Sry

**Comment by hiradimir** [comment]
@RobinBuschmann Thank you for reply.
Now, I do not use extends model.

----

And now, I am analyzing sequelize-typescript, but it is difficult for me...

**Comment by RobinBuschmann** [comment]
@hiradimir Regarding this issue, I'am already fixing it.

For any further help I'm happy, too. If you have questions, don't hesitate to ask.

**Comment by hiradimir** [comment]
@RobinBuschmann Thanks for fix, thanks for comment!

I'll use seqeulize-typescript more!
