### ISSUE TITLE
Model not initialized: TeamModel cannot be instantiated. "TeamModel" needs to be added to a Sequelize instance.

### ISSUE THREAD

**Issue by whitestranger7** [RobinBuschmann/sequelize-typescript#771]
Hello, sequelize-typescript devs, I've got a weird error, which is, well... pretty weird. So that's my situation:

1. I have DBcontext.ts file, which is represents the whole logic behind about sequelize instance and all it's functions. I've created sequelize instance as a class with some publick methods like that:
`import { Sequelize, Repository, Model } from 'sequelize-typescript';
import { UserModel } from './models/user.model';
import { TeamModel } from './models/team.model';
import { GameModel } from './models/game.model';
import { RoundModel } from './models/round.model';
import { GameDayModel } from './models/game-day.model';
import { GridModel } from './models/grid.model';
import { PlayoffModel } from './models/playoff.model';
import { TournamentModel } from './models/tournament.model';
import { TeamStatisticModel } from './models/team-statistics.model';

export class DbContext {
  private _sequelize: Sequelize;
  constructor() {
    this._sequelize = new Sequelize({
      repositoryMode: true,
      dialect: 'postgres',
      database: 'sunmait_tournament',
      username: 'root',
      password: 'root',
      host: 'localhost',
      port: 5432,
      models: [UserModel, TeamModel, GameModel, GameDayModel, RoundModel, GridModel, PlayoffModel, TournamentModel, TeamStatisticModel]
    });
  }

  public async connect(): Promise<void> {
    await this._sequelize.authenticate();
  }
}` 

2. This public connect() method I used to initialize sequelize and apply it to my server in server.ts:
`import express from 'express';
import api from './routes';
import { DbContext } from './db/DbContext';

const app = express();
const db = new DbContext();
app.use(express.json());
app.use('/api', api);

(async () => {

  db.connect();

  const port = 5000;
  app.listen(port, () => {
    console.info(`Server is started in ${port}`);
  });
})()`

3. All models in sequelize constructor in DBcontext.ts are appropriate and added to models field.
Here's example of one TeamModel which is added to sequelize instance models array.

`@Table({
  tableName: 'teams',
})
export class TeamModel extends Model<TeamModel> {
  @PrimaryKey
  @Column({
    allowNull: false,
    autoIncrement: true,
    primaryKey: true,
    type: DataType.INTEGER,
  })
  id!: number;

  @Column({
    allowNull: false,
    type: DataType.STRING,
  })
  title!: string;

  @Column({
    allowNull: false,
    type: DataType.BOOLEAN,
  })
  is_active!: boolean;

  @HasOne(() => TeamStatisticModel)
  statistic!: TeamStatisticModel;

  @ForeignKey(() => TournamentModel)
  @Column({
    type: DataType.INTEGER,
    defaultValue: null
  })
  tournament_id!: number;

  @HasMany(() => UserModel)
  members!: UserModel[];

  @CreatedAt
  creation_date!: Date;

  @UpdatedAt
  updated_on!: Date;

  @DeletedAt
  deletion_date!: Date;
}`

It works fine. When sequelized.authenticate() called, there are no problems and everything works good. But when I try to create an instance of this TeamModel like this:

` const team = new TeamModel({title, tournament_id, creation_date: new Date(), updated_on: new Date(), deletion_date: null});` or ` const team = TeamModel.build({title, tournament_id, creation_date: new Date(), updated_on: new Date(), deletion_date: null});`

Appears the error from the title:

`(node:16052) UnhandledPromiseRejectionWarning: Error: Model not initialized: TeamModel cannot be instantiated. "TeamModel" needs to be added to a Sequelize instance.
    at new Model (C:\Users\Иван\Desktop\snmt-tournament\server\node_modules\sequelize-typescript\dist\model\model\model.js:11:19)        
    at new TeamModel (C:\Users\Иван\Desktop\snmt-tournament\server\src\db\models\team.model.ts:21:1)
    at DbContext.test (C:\Users\Иван\Desktop\snmt-tournament\server\src\db\DbContext.ts:32:18)
    at C:\Users\Иван\Desktop\snmt-tournament\server\src\server.ts:13:6
    at Generator.next (<anonymous>)
    at C:\Users\Иван\Desktop\snmt-tournament\server\src\server.ts:8:71
    at new Promise (<anonymous>)
    at __awaiter (C:\Users\Иван\Desktop\snmt-tournament\server\src\server.ts:4:12)
    at C:\Users\Иван\Desktop\snmt-tournament\server\src\server.ts:10:13
    at Object.<anonymous> (C:\Users\Иван\Desktop\snmt-tournament\server\src\server.ts:19:3)
    at Module._compile (internal/modules/cjs/loader.js:1158:30)
    at Module._compile (C:\Users\Иван\Desktop\snmt-tournament\server\node_modules\source-map-support\source-map-support.js:541:25)       
    at Module.m._compile (C:\Users\3C8A~1\AppData\Local\Temp\ts-node-dev-hook-9070666193298011.js:57:25)
    at Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
    at require.extensions.<computed> (C:\Users\3C8A~1\AppData\Local\Temp\ts-node-dev-hook-9070666193298011.js:59:14)
    at Object.nodeDevHook [as .ts] (C:\Users\Иван\Desktop\snmt-tournament\server\node_modules\ts-node-dev\lib\hook.js:61:7)
    at Module.load (internal/modules/cjs/loader.js:1002:32)
    at Function.Module._load (internal/modules/cjs/loader.js:901:14)
    at Module.require (internal/modules/cjs/loader.js:1044:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at Object.<anonymous> (C:\Users\Иван\Desktop\snmt-tournament\server\node_modules\ts-node-dev\lib\wrap.js:80:1)
    at Module._compile (internal/modules/cjs/loader.js:1158:30)`

What's am I doing wrong?

**Comment by sgoff0** [comment]
@whitestranger7  I had this same error and saw I was missing `models: [__dirname + '/models']` completely.

I do see you already have models defined so it may not the the problem
```js
models: [UserModel, TeamModel, GameModel, GameDayModel, RoundModel, GridModel, PlayoffModel, TournamentModel, TeamStatisticModel]
```

but have you tried importing the model directory per [the sequelize-typescript-example](https://github.com/RobinBuschmann/sequelize-typescript-example/blob/cb1e675c9cd8a6df8955c81a3dedfb02b7cc4a31/lib/sequelize.ts#L7)?

**Comment by GoygovRustam** [comment]
I was able to fix this by calling **build** on the Repository and not on the Model
