### ISSUE TITLE
Unable to import Model with Node.js 13/14 ES Modules

### ISSUE THREAD

**Issue by brycekahle** [RobinBuschmann/sequelize-typescript#782]
**Versions**

- sequelize: 5.21.7
- sequelize-typescript: 1.1.0
- typescript: 3.8.3
- Node.js: 13.14.0 or 14.2.0

**I'm submitting a ...** 

[x] bug report
[ ] feature request

**Actual behavior:**

When attempting to run only the following code with Node.js 13 or 14
```ts
import { Model } from 'sequelize-typescript';
console.log(Model);
```
I received the following error:
```
import { Model } from 'sequelize-typescript';
         ^^^^^
SyntaxError: The requested module 'sequelize-typescript' does not provide an export named 'Model'
    at ModuleJob._instantiate (internal/modules/esm/module_job.js:92:21)
    at async ModuleJob.run (internal/modules/esm/module_job.js:107:20)
    at async Loader.import (internal/modules/esm/loader.js:179:24)
```

My `package.json` does have `"type": "module"`.

It is unclear whether this is a problem with how `sequelize-typescript` is built, or a problem with Node.js ES modules itself, but I was unable to discover the root issue.

**Expected behavior:**
`Model` is a valid import.

**Steps to reproduce:**

Run the code as described above with Node.js 13 or 14, alongside a `package.json` with `"type": "module"`.

**Comment by dcsan** [comment]
did you solve this? i'm having slightly similar weird behavior as in https://github.com/sequelize/sequelize-typescript/issues/1369

**Comment by Beace** [comment]
@dcsan  I ended up using  `skipLibCheck`. But not a perfect solution.
