### ISSUE TITLE
How to resolve the associations?

### ISSUE THREAD

**Issue by bucket-sven** [RobinBuschmann/sequelize-typescript#80]
Hello,
I have two models, in `profile.ts`:

```js
import User from './user'
export default class Profile extends Model<Profile> {
  @BelongsTo(() => User)
}
```

in `user.ts`:
```js
import Profile from './profile'
export default class User extends Model<User> {
  @HasOne(() => Profile)
}
```

But, there are cyclic dependencies. How can I resolve this? Thank you.

**Comment by RobinBuschmann** [comment]
Hey @bucket-sven, you don't need to. Node.js and the fact that lambda's are used instead of class references does this for you. So your example should work very well like it is.

Or do you face some issues with your example?

**Comment by bucket-sven** [comment]
Hi, @RobinBuschmann , 

Now I found that, if I use `@BelongsTo` and `@HasOne` at the same time, it will throw exceptions.
Like the example I gave before,  if I remove `@BelongsTo` from `profile.ts`, or remove `@HasOne` from `user.ts`, it does work. But if they exist at the same time, it will throw errors like below:

  
```
/Users/sven/Node/type/demo/node_modules/sequelize/lib/associations/mixin.js:80
    if (!target.prototype || !(target.prototype instanceof this.sequelize.Model)) {
               ^
TypeError: Cannot read property 'prototype' of undefined
    at Function.<anonymous> (/Users/sven/Node/type/demo/node_modules/sequelize/lib/associations/mixin.js:80:16)
    at Function.target.(anonymous function) [as belongsTo] (/Users/sven/Node/type/demo/node_modules/sequelize-typescript/lib/models/BaseModel.js:49:37)
    at /Users/sven/Node/type/demo/node_modules/sequelize-typescript/lib/models/BaseSequelize.js:101:44
    at Array.forEach (native)
    at /Users/sven/Node/type/demo/node_modules/sequelize-typescript/lib/models/BaseSequelize.js:71:26
    at Array.forEach (native)
    at Sequelize.BaseSequelize.associateModels (/Users/sven/Node/type/demo/node_modules/sequelize-typescript/lib/models/BaseSequelize.js:67:16)
    at Sequelize.BaseSequelize.addModels (/Users/sven/Node/type/demo/node_modules/sequelize-typescript/lib/models/BaseSequelize.js:54:14)
    at Object.<anonymous> (/Users/sven/Node/type/demo/src/stay/AppUserLogin.ts:27:11)
    at Module._compile (module.js:569:30)
    at Module.m._compile (/Users/sven/Node/type/demo/node_modules/ts-node/src/index.ts:392:23)
    at Module._extensions..js (module.js:580:10)
    at Object.require.extensions.(anonymous function) [as .ts] (/Users/sven/Node/type/demo/node_modules/ts-node/src/index.ts:395:12)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/sven/Node/type/demo/src/stay/AppUser.ts:8:1)
    at Module._compile (module.js:569:30)
    at Module.m._compile (/Users/sven/Node/type/demo/node_modules/ts-node/src/index.ts:392:23)
    at Module._extensions..js (module.js:580:10)
    at Object.require.extensions.(anonymous function) [as .ts] (/Users/sven/Node/type/demo/node_modules/ts-node/src/index.ts:395:12)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/sven/Node/type/demo/test/src/stay/AppUser.ts:3:1)
    at Module._compile (module.js:569:30)
    at Module.m._compile (/Users/sven/Node/type/demo/node_modules/ts-node/src/index.ts:392:23)
    at Module._extensions..js (module.js:580:10)
    at Object.require.extensions.(anonymous function) [as .ts] (/Users/sven/Node/type/demo/node_modules/ts-node/src/index.ts:395:12)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at /Users/sven/Node/type/demo/node_modules/mocha/lib/mocha.js:230:27
    at Array.forEach (native)
    at Mocha.loadFiles (/Users/sven/Node/type/demo/node_modules/mocha/lib/mocha.js:227:14)
    at Mocha.run (/Users/sven/Node/type/demo/node_modules/mocha/lib/mocha.js:513:10)
    at Object.<anonymous> (/Users/sven/Node/type/demo/node_modules/mocha/bin/_mocha:480:18)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Function.Module.runMain (module.js:605:10)
    at startup (bootstrap_node.js:158:16)
    at bootstrap_node.js:575:3
```

**Comment by RobinBuschmann** [comment]
@bucket-sven Can you provide me a full example please? Thank you

**Comment by bucket-sven** [comment]
@RobinBuschmann  OK，

In `index.ts`,
```js
import { Sequelize } from 'sequelize-typescript'
import * as config from '../../config/database'

const sequelize = new Sequelize(config.stay as any)

export default sequelize
```

In `AppUser.ts`,

```js
import {
  Table,
  Column,
  Model,
  HasOne,
  DataType
} from 'sequelize-typescript'
import AppUserLogin from './AppUserLogin'
import sequelize from './'

@Table({
  tableName: 'app_user'
})
export default class AppUser extends Model<AppUser> {
  @HasOne(() => AppUserLogin, 'userId')
  login: AppUserLogin
}
sequelize.addModels([AppUser])
```

In `AppUserLogin.ts`,

```js
import {
  Table,
  Column,
  Model,
  ForeignKey,
  BelongsTo,
  DataType
} from 'sequelize-typescript'
import sequelize from './'
import AppUser from './AppUser'

@Table({
  tableName: 'app_user_login'
})
export default class AppUserLogin extends Model<AppUserLogin> {
  @ForeignKey(() => AppUser)
  @Column({
    type: DataType.BIGINT,
    field: 'user_id'
  })
  userId: number
  @BelongsTo(() => AppUser, 'userId')
  user: AppUser
}
sequelize.addModels([AppUserLogin])
```

It will throw exception I wrote before when I call `AppUser.find<AppUser>()` in my test code.

How can I do with it?  Thank you.

**Comment by RobinBuschmann** [comment]
@bucket-sven The error already occurs on `addModels`, right?

You need to add them at once, because sequelize-typescript tries to resolve the associations defined by `@HasOne`, `@BelongsTo` and so on after adding them.

So a better approach would be to add them externally (not in the corresponding model files):
```typescript
const sequelize = new Sequelize({modelPaths: ['path/to/models-folder']})
```
or
```typescript
const sequelize = new Sequelize({modelPaths: [AppUser, AppUserLogin]})
```

**Comment by bucket-sven** [comment]
@RobinBuschmann  Yeah, it works! Thank you very much!
