### ISSUE TITLE
HasMany relations problems!  Alias cannot be inferred: "Comments" has multiple relations with "User" 

### ISSUE THREAD

**Issue by CGerAJ** [RobinBuschmann/sequelize-typescript#822]
Versions

sequelize: 5.22.2
sequelize-typescript: 1.1.0
typescript ^3.7.4
I'm submitting a ...
[x] bug report
[ ] feature request

Issue:

tables
```
@Table
export class User extends Model<User> {
  @Column({ primaryKey: true, autoIncrement: true, comment: 'id' })
  id: number;

  @Column
  firstName: string;

  @Column
  lastName: string;

  @Column({ defaultValue: true })
  isActive: boolean;

  @HasMany(() => Post)
  posts: Post[];

  @HasMany(() => Comments, 'CommentsUser')
  commentsUserId: Comments[];

  @HasMany(() => Comments, 'CommentsTargetUser')
  commentsTargetUserId: Comments[];
}


@Table
export class Comments extends Model<Comments> {
  @Column({ primaryKey: true, autoIncrement: true, comment: 'id' })
  id: number;

  @Column
  content: string;

  @ForeignKey(() => User)
  @Column
  userId: number;

  @BelongsTo(() => User, 'CommentsUser')
  user: User;

  @ForeignKey(() => User)
  @Column
  targetUserId: number;

  @BelongsTo(() => User, 'CommentsTargetUser')
  targetUser: User;
}
```

Here is a detailed document, but I still get the error according to the document configuration。

https://github.com/RobinBuschmann/sequelize-typescript#multiple-relations-of-same-models

where i use 

```
this.sequelize.getRepository(Comments).findAll({
      include: [
        {
          model: User,
          association: 'CommentsUser',
        },
        {
          model: User,
          association: 'CommentsTargetUser',
        },
      ],
    });
```

error message
```
Alias cannot be inferred: "Comments" has multiple relations with "User" +1802ms
Error: Alias cannot be inferred: "Comments" has multiple relations with "User"
    at inferAliasForInclude (/Users/xiangyujie/www/sequelize-foreignkey-demo/node_modules/sequelize-typescript/dist/associations/alias-inference/alias-inference-service.js:44:23)
    at /Users/xiangyujie/www/sequelize-foreignkey-demo/node_modules/sequelize-typescript/dist/associations/alias-inference/alias-inference-service.js:22:19
    at Array.map (<anonymous>)
    at Object.inferAlias (/Users/xiangyujie/www/sequelize-foreignkey-demo/node_modules/sequelize-typescript/dist/associations/alias-inference/alias-inference-service.js:21:39)
    at Function.Model.<computed> [as findAll] (/Users/xiangyujie/www/sequelize-foreignkey-demo/node_modules/sequelize-typescript/dist/model/model/model.js:128:59)
```

**Comment by sluchznak** [comment]
any changes here?

**Comment by pramod9254** [comment]
@ForeignKey(() => User)
  @Column
  userId: number;

  @BelongsTo(() => User, 'userId')
  user: User;

  @ForeignKey(() => User)
  @Column
  targetUserId: number;

  @BelongsTo(() => User, 'targetUserId')
  targetUser: User;

**Comment by hoanghuychh** [comment]
How to fix these issues?
